### ISSUE TITLE
Include add/remove fan factor to admin actions on roster page

### ISSUE THREAD

**Issue by Shteve0** [TheNAF/naflm#1]
Requested by user

**Comment by rythos42** [comment]
My league commissioner just requested this one as well.

**Comment by hutchinsfairy** [comment]
I've just got this working but there's a wrinkle. OBBLM dynamically calculates the team's FF based on the starting value and then FF earned in subsequent matches.

What I have so far is to allow the admin to change the starting amount but this cannot be a negative value (database restriction I presume). This would mean that you could essentially never reduce the team's FF below what they have earned on the field.

Is this what is needed?

**Comment by rythos42** [comment]
I explained the restrictions to my commissioner, and he asked a lot of questions about why and how it would be so much better to have free access to change it. 

Then I asked for his use cases, and he explained the issues he was trying to solve, and every case he mentioned was solvable with your solution...so...I feel like this is a case of the user `wanting` more than they really `need`. We started tracking our league in OBBLM after the league started, so there was a painful period when he manually entered in a ton of fake games to make the numbers line up. He also wanted to be able to give 1-time bonus' to players (like for having fully painted rosters).

So I think you've covered my leagues needs at least! :)

**Comment by Shteve0** [comment]
Yep, I think that would also cover the needs of the other request (Basildon
Warboys)

**Comment by hutchinsfairy** [comment]
Added as pull request #53

**Comment by dannyuk1982** [comment]
Any way to add negative values?

Use case: end of a season all fan factor > 5 are reset to 5

**Comment by rythos42** [comment]
No, unfortunately the best you can do is to adjust FF up, with the baseline being the amount of FF the user has accrued in their games.

Trying to do otherwise would be a big overhaul that the current developers don't have time for. :(

**Comment by dannyuk1982** [comment]
Thanks Craig, thought this might be the case - I had a look myself to see why it couldn't handle this but a lot of the code to calc things seems to be in the MySQL?! Gave up after an hour of looking where it was added up
