### ISSUE TITLE
Normalize settings_1.php

### ISSUE THREAD

**Issue by jgmorse** [TheNAF/naflm#100]
settings_1.php is missing function calls that are present in settings_2.php and necessary for site functionality, e.g.

`$get_prime = get_alt_col('league_prefs','f_lid',$get_lid,'prime_tid');
$get_second = get_alt_col('league_prefs','f_lid',$get_lid,'rules_tid');`

This presents a problem for new installers who are migrating data from their obblm databse and using league ID 1.

I have a clean install with this and #98  and #99 implemented if you'd like me to submit a pull request.

**Comment by rythos42** [comment]
I'd love a pull request. :D

**Comment by rythos42** [comment]
Actually, looking at this stuff, what I'd reaaaaally like is to get the settings files organized a bit better. 

- Delete settings_2.php, there don't need to be 2 of them in the repo. 
- Add settings_1.php to Gruntfile.js ignore line so it's never deployed to thenafdev.
- Remove settings_X.php from .gitignore. settings_1 is a code file that belongs in the repo, it shouldn't be ignored. At the same time, devs must be careful not to commit (by setting `assume-unchanged` on it). (part of #99)
- I think I also want to move settings.php from the root to localsettings, and delete config.php. (part of #101). Then localsettings can be the folder that contains all the files that developers shouldn't commit (unless they are adding a setting, and commit an "example" of that setting).

**Comment by rythos42** [comment]
On the other hand, settings_1 does need updating, so there it is. :)

**Comment by rythos42** [comment]
Thinking about upgrading admins -- moving settings.php is a bad idea so I'm leaving it where it is. 

Devs will just have to remember settings.php and settings_X.php shouldn't be committed (or should be set `assume-unchanged`).
