### ISSUE TITLE
Troubleshooting page for league, division, tournament IDs

### ISSUE THREAD

**Issue by rythos42** [TheNAF/naflm#104]
Some sort of troubleshooting page that lists all the league, division and tournament IDs and is viewable to general users. Doesn't need to be linked to the menu, just an /IDs.php extension maybe? Doesn't even need to be anything other than a list on a white page.

**Comment by rythos42** [comment]
/troubleshoot.php

**Comment by hutchinsfairy** [comment]
Closes #6?

**Comment by rythos42** [comment]
It does! I didn't notice that old one. >.<
