### ISSUE TITLE
League override stylesheet not loaded until after first load

### ISSUE THREAD

**Issue by rythos42** [TheNAF/naflm#108]
Looks like the <stylesheet> tag is being rendered as "league_override_.css" on first load and "league_override_3.css" on second load on WBBL.

**Comment by rythos42** [comment]
@Shteve0 This should/could be fixed. Try grabbing `class_htmlout.php` and see if it fixes your issue?

**Comment by Shteve0** [comment]
Nice mate. I'll check it out this evening.

Have you ever seen an error where the skills all appear twice in the
selection list, by the way? Since upgrading I have that on WBBL... I'll
send you a commish login later

**Comment by Shteve0** [comment]
Confirmed the stylesheet issue appears to be fixed.  Excellent stuff!
