### ISSUE TITLE
Request: method of switching house rosters on and off in LeaguePref

### ISSUE THREAD

**Issue by Shteve0** [TheNAF/naflm#11]
Low priority

**Comment by Shteve0** [comment]
Priority change - move up to high following Sunday's NAF committee meeting agreement to allow pre-selected house rosters as optional includes for NAF leagues (mirroring core obblm functionality).

In League Pref or in Tournament admin; we'll want the option to allow additional rosters (khorne, for example) as selectable for this league/division/tournament.

This can't be done with turning on and off the core game data files as we need them to be loaded for all leagues if they are to be used by any.  Proposal at this stage is that commissioner may 'activate' for their league as opt in basis.  This in practice will, I guess, mean creating a flag on the l/d/t container and then performing a check to that flag when a team is created (against the coach's leagues, for example) or added to a tournament (if the flag is at tournament level).

**Comment by Shteve0** [comment]
Refer #182

**Comment by ZerosGiven** [comment]
So is the plan to be able to turn on and off new rosters? So we could add, for example these new Savage Orcs and have it as a easy to turn on and off switch? From my point of view, things like this would make this OBBLM system so much easier to use. It's clear GW are going to be throwing out these things going forward over periods of time, so to be able to just add them in easy and turn them on and off would be great, same with Star Players I guess.

I could of course be holding the wrong end of the stick here though so please let me know if I am.

**Comment by Shteve0** [comment]
You understood my intention exactly correctly :)

**Comment by hutchinsfairy** [comment]
Longer term I think the best design would be to have a Races table and a per-league admin page to maintain them. It would be a big piece of work to move away from the game data files but has to be better than having to keep updating core NAFLM for every experimental team that GW want to try out.

Much better to initialise each new league with a standard set of races and then leave it up to the league commish to change them as they see fit. This would also allow NAFLM to be used for things like Stunty Leeg or Narrow Tier leagues. It would also accomodate leagues wishing to remain on LRB6.

Of course that's easy for me to say as I won't be the one doing any work...
