### ISSUE TITLE
Request: Coach profile on coach page

### ISSUE THREAD

**Issue by hutchinsfairy** [TheNAF/naflm#111]
When clicking on a coach's name (e.g. on team page) you get taken to a list of that coach's other teams. Could you also include the profile information?

E.g. for Shteve0 on the dev site:

Could [this](http://thenafdev.obblm.com/index.php?section=objhandler&type=1&obj=3&obj_id=182) page also include [this](http://thenafdev.obblm.com/index.php?section=objhandler&type=1&obj=3&obj_id=182&subsec=profile) info?

**Comment by hutchinsfairy** [comment]
Mostly this is for easy access to other coaches' full names and email addresses so I can contact them to arrange league matches or cross reference their names with our forum users to contact them that way.

**Comment by rythos42** [comment]
Yeah, seems reasonable!

**Comment by hutchinsfairy** [comment]
Just a thought related to this. Do coaches know that their email address will be accessible to other logged in coaches? Should there be some wording to that effect on the registration page?

**Comment by rythos42** [comment]
Seems like the polite thing to do, yeah. 

We could also reduce the e-mail visibility to only for Commissioner and above, if that still meets the needs of the request? My league has a Whatsapp group we use (*constantly*). :)

**Comment by hutchinsfairy** [comment]
This request came about specifically because I needed to email another coach to arrange a match so >=commish wouldn't work for that. My ideal solution would be an option to message another coach via NAFLM and so not expose their email address but that's probably a bit beyond scope.

Making email addresses easier to find and warning coaches what that means seems like a quicker win.

**Comment by rythos42** [comment]
Ok. We could still do a "message via NAFLM" thing, as we don't necessarily need to build an entire messaging infrastructure to go along with it. Something similar to how I built "Request a League" -- it's just a simple form that sends an e-mail on behalf of the user. 

E-mail addresses is still simpler, for sure.

I don't currently plan on work on this feature (enough other stuff to do!) so for whomever does this, whatever they feel like should be great!

**Comment by hutchinsfairy** [comment]
Was just looking at something else and realised that 0.91 had this already so it seems like it might have been lost. See [this](http://thenaf.obblm.com/index.php?section=objhandler&type=1&obj=3&obj_id=182&subsec=profile) for example.

**Comment by rythos42** [comment]
Does that page cover what you were looking to have?

**Comment by Shteve0** [comment]
Lost how?

http://thenafdev.obblm.com/index.php?section=objhandler&type=1&obj=3&obj_id=182&subsec=profile

**Comment by Shteve0** [comment]
Ah, I see! There's no way to find that page from the menu (oops).

Okay, so we just need a link from this page (for each coach):
http://thenafdev.obblm.com/index.php?section=objhandler&type=1&obj=3&obj_id=182

To their profile page:
http://thenafdev.obblm.com/index.php?section=objhandler&type=1&obj=3&obj_id=182&subsec=profile

**Comment by hutchinsfairy** [comment]
Yes, but it appears that we have that link (and some others) in 0.91.

**Comment by Shteve0** [comment]
Tom, what else is missing? If we roll it into one ticket I can take a look
this week.

**Comment by hutchinsfairy** [comment]
Basically, can the coach page go back to how it was in 0.91?
i.e. [NAFDev](http://thenafdev.obblm.com/index.php?section=objhandler&type=1&obj=3&obj_id=182) VS [NAF](http://thenaf.obblm.com/index.php?section=objhandler&type=1&obj=3&obj_id=182)

**Comment by Shteve0** [comment]
Yeah, if you just override /lib/class_coach_htmlout.php with the latest obblm version it comes out like this:

![screenshot 2016-05-04 at 19 10 35](https://cloud.githubusercontent.com/assets/13360859/15007304/ef8e72f8-122b-11e6-85f2-37c9b63a96bb.png)

I'm on the fence.  For or against?

**Comment by rythos42** [comment]
I think that removing existing functionality is a bad idea, so we should find out what change removed this option, and fix it.

**Comment by Shteve0** [comment]
I did this, I'm pretty sure.  Looking back, perhaps I shouldn't have done so.

When I rebuilt the main menu I took this one out, I think because of the page load order the main menu was being overlaid by the coach menu.

How do we feel about the list version in the screenshot? It just means restoring the original file.

**Comment by hutchinsfairy** [comment]
I'm always for function over form so my vote would be to bring it back, especially if it's not much work.

**Comment by rythos42** [comment]
You can't "just restore the original file", there's a lot of changes to that file since we forked! If we want this fixed, we do need to figure out what caused the change and to commit a change _just for that._

**Comment by Shteve0** [comment]
Ha, you're right.

It's this change: https://github.com/TheNAF/naflm/commit/5acac7d600f3717120dfb5b105eae5d8ae694a8d#diff-424e63c4cebcf7e20dfcf9efa76cbe2e

**Comment by rythos42** [comment]
Thanks for finding that, Steve! I put this code back, styled it a bit and made sure it was under the main menu (as opposed to "on top of").

I'm not happy about having multiple items with the ID "css3menu1" on the page, but am not prepared to make that change right now. I'll log a tech issue for it.
