### ISSUE TITLE
Mobile: Touching out of player section resets player (and doesn't update)

### ISSUE THREAD

**Issue by rythos42** [TheNAF/naflm#113]
That's a terrible title...

Steps:

1. Open mobile, open a match.
1. Select a player other than the first player.
1. Give them an input -- MVP, CP, whatever.
1. Touch (maybe click?) into the Treasury section (I believe anything in the above section will work)

*Expected:* Nothing changes on screen except the focus. 
*Actual:* The player selection drop down resets to player 1, and when you select the previous player from step 2, the input you gave them isn't reflected in the UI.

**Comment by hutchinsfairy** [comment]
Could you submit an update on field change events (as seems to be increasingly common for mobile interfaces) but not mark the match as played (as per #55)? You could then save some screen real estate by not having a save button.

**Comment by rythos42** [comment]
We could, but I feel very unsettled whenever I close something that I haven't explicitly saved. I feel like the user wants a Save button to feel safe that their data was saved.

However, this issue is actually just a bug. If you enter something for a player, then touch anywhere else on the screen it resets the player selection without holding onto the change that the player made. 

I guess I was confusing when I said "input is not saved" -- the issue isn't that it "isn't being saved to the server". The interface is that you input something, then that input is "saved" in the JavaScript, and later written to the server when the user presses the Save button. That "JavaScript save" isn't happening, so if you do more than one thing on the dialog, the first thing you do won't be kept.

**Comment by hutchinsfairy** [comment]
You needed a longer title then obviously :)

**Comment by rythos42** [comment]
Yes, and to use my excellent QA skills to write better repro steps. :P I changed the Expected and Actual above to hopefully clarify what I meant!
