### ISSUE TITLE
Leagueprefs table entry required on upgrade

### ISSUE THREAD

**Issue by Shteve0** [TheNAF/naflm#116]
When running upgrade.php, need a check for existing leagues and a row inserted with dummy data into the table. Not having this means it needs to be a manual step for the user otherwise the leagueprefs menu does weird stuff (I managed to botch my WBBL site trying to use it without the table entry and caused a redirect loop)

**Comment by rythos42** [comment]
What do you mean when you say "the leagueprefs menu does weird stuff"? The current implementation creates this table row when the user navigates to the league prefs area and clicks save. Is there a place where the information here is needed before the user clicks save? It is probably easier to do a check at that point, rather than creating dummy data.

**Comment by Shteve0** [comment]
Oh, I didn't realise you'd made that change. In theory that's fine.

I installed the update on an existing website, and when I went into
leagueprefs and tweaked the css, then hit save, I got kicked into a
redirect loop. I checked the db and there was no leagueprefs row for the
league, so I assumed we'd just missed that step.

What query are you using to insert the row?
On 3/05/2016 5:18 am, "Craig Fleming" <notifications@github.com> wrote:

What do you mean when you say "the leagueprefs menu does weird stuff"? The
current implementation creates this table row when the user navigates to
the league prefs area and clicks save. Is there a place where the
information here is needed before the user clicks save? It is probably
easier to do a check at that point, rather than creating dummy data.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/TheNAF/naflm/issues/116#issuecomment-216299578>

**Comment by Shteve0** [comment]
Closing this.  I just managed to replicate the redirect loop I thought was caused by the leagueprefs menu by copying too much of the github page into a php file, so I'm going to write this off as a screw up on my part.
