### ISSUE TITLE
Forum URL not correct

### ISSUE THREAD

**Issue by rythos42** [TheNAF/naflm#122]
I did find a problem with the Forum URL, it contains the complete URL for obblm then the complete URL for the forum...

http://www.mondayknights.org.au/obblm/www.mondayknights.org.au/forum

**Comment by rythos42** [comment]
Just wasn't dealing properly with URLs of the form "www.google.ca", needed an "http://" appended to the front of any that didn't have it.

At the same time, there's only so much we can do to help people out with this field.

**Comment by Shteve0** [comment]
Yeah, I picked this up recently and mucked around with it until I found a
combo that worked.

Could we add a helper line to the field name maybe?  Not necessarily a
hover over, just in the form similar to the instructions under the custom
css entry.

**Comment by rythos42** [comment]
I don't think it's necessary. I made it so that it'll add the stuff required to an invalid address, and then it's up to the user to enter an address that actually goes somewhere. Someone would have to mess up pretty badly to get it wrong, I think.

**Comment by Shteve0** [comment]
Oh sweet, I didn't realise you'd added that.  Good stuff!
