### ISSUE TITLE
Renaming and numbering players

### ISSUE THREAD

**Issue by thefloppy1** [TheNAF/naflm#134]
Coaches can rename any player, not just the ones on their own teams. 
This also applies to renumbering.

Any coach can rename or renumber any teams players. #131 #132

**Comment by thefloppy1** [comment]
And they can rename Dead players

**Comment by rythos42** [comment]
Thanks, I'll get to this.

**Comment by rythos42** [comment]
I wanted a stop-gap measure here since I re-introduced the feature to dev, but I'm not happy with the current solution. Too much information in a generic function, I'll find a way to get it back out again.

**Comment by rythos42** [comment]
Like all good ideas, this one got better the more I let it sit. Reasonably happy with the controls now.
