### ISSUE TITLE
Fatal error: Call to a member function isMyTeam() in class_team_htmlout.php

### ISSUE THREAD

**Issue by thefloppy1** [TheNAF/naflm#143]
Find this error only when you are not logged in, and clicking on a team you wish to view.

Fatal error: Call to a member function isMyTeam() on null in /lib/class_team_htmlout.php on line 505

Not a big problem, but nice to fix if people want leagues teams viewable by general public.

**Comment by rythos42** [comment]
Thanks for catching this! It's fixed now. I assumed `$coach` would always have a value, when it clearly doesn't if a user isn't logged in.
