### ISSUE TITLE
Should menu be split to new module?

### ISSUE THREAD

**Issue by Shteve0** [TheNAF/naflm#15]
Menus currently hardcoded into htmlout.php files in lib.  Should these be split for easier customisation?

Also need to amend to call entries in translation files as non-english likely an issue

**Comment by Shteve0** [comment]
Low priority

**Comment by williamleonard** [comment]
I rewrote the module system and the htmlout.php to automate the process of building the menus.  I will try to find it.  It allowed a spot in any module to put in a menu variable and the module system would use that to build out the menu.  So there isn't a need to move it from the current spot, just rewrite a little.

**Comment by Shteve0** [comment]
Excellent.  I've previously re-ordered the menu to make it more intuitive (or try to).  Perhaps once the dust settles we can revisit.

**Comment by rythos42** [comment]
Are we happy with the current menu system? It's not perfect, but it seems good enough.

I'm interested in making the Home/Leagues section built up from the database, so that a new league doesn't need to be manually added to the HTML.

**Comment by Shteve0** [comment]
Cool. I'm open to changing it, if needs be, but I'm fairly happy with how
it works now (other than the home/leagues bit).

If we go for the build from database, ideally it'll only kick in for two or
more leagues.

**Comment by rythos42** [comment]
This was the last item to be done to make League creation entirely within the UI and not have any external FTP or GitHub processes.

Now the Home menu is built using the league Location field. We've chosen to make this field be "Counties", but it could be anything for other users.

But be warned -- if you put "Vancouver, BC, Canada" as a Location for a league, that entire string will appear in the Home menu!

**Comment by Shteve0** [comment]
Countries?
