### ISSUE TITLE
Error with PDF Generation

### ISSUE THREAD

**Issue by mfranchetti** [TheNAF/naflm#159]
From [TFF](http://talkfantasyfootball.org/viewtopic.php?f=29&t=43078&p=761816#p761816):
![obblm pdf](https://cloud.githubusercontent.com/assets/11505434/17246203/79d1d3bc-5582-11e6-85cd-02f0a0e18e43.PNG)

I've had a quick look at believe that the ob_clean() function call on line 994 is returning an error. As the error message has already been sent as output, the attempt to change the header on line 1018 is failing which prevents the PDF generation.
the ob_clean() function empties the current output buffer and the error message is reporting that it is already empty. Not sure why your install should be doing this when other don't but should be resolvable by using ob_get_length() to check if the buffer needs emptied first.

I recommended replacing line 994 with:

```
if (ob_get_length())
    ob_clean();
```

I haven't been able to reproduce the error - might be worth waiting on feedback before implementing in NAFLM.

**Comment by Shteve0** [comment]
This error is generally due to a space or line carry in the at the end of
one of the php files - ie after the final ?>

**Comment by mfranchetti** [comment]
I think in this case it's actually because there isn't that extra space. ob_clean is called to clear those extra spaces from the output buffer. The error message suggests that the buffer is empty in this case.
