### ISSUE TITLE
Login needed when clicking "New User Registration" link from e-mail

### ISSUE THREAD

**Issue by rythos42** [TheNAF/naflm#163]
This one bugs me every time. You get an e-mail about New User Registration and it has a link to go to the user administration page. You click it, and it says you have to login. If I were to open TheNAF just in a new browser window, it would have me logged in, but something about this link and flow doesn't work!

**Comment by Shteve0** [comment]
Same!  Good call on this.

**Comment by Shteve0** [comment]
I think #164 will replace the need for this?
