### ISSUE TITLE
Replace mysql_connect(), etc

### ISSUE THREAD

**Issue by rythos42** [TheNAF/naflm#171]
This PHP function has been deprecated since 5.5 and is removed in 7.0. http://php.net/manual/en/function.mysql-connect.php

There are likely upgrade guides around the internet that can walk us through exactly what needs fixing, since I doubt (without having looked) that mysql_connect() is the only piece that's removed.

Not currently a high priority, since our host will be unlikely to remove <7.0 functionality for a while, but it needs to be done at some point, so I log it.

**Comment by dannyuk1982** [comment]
This is pretty simple, just change mysql_whatever to mysqli_whatever in most cases. Really it needs converting to use a wrapper though, so i.e. $mywrapper->query() instead of mysql_query(), then changes can be made in the future at any point - i.e. you could change to use PDO.

**Comment by jeremycobert** [comment]
Has this been addressed and updated in any recent versions of NAFLM ?

**Comment by rythos42** [comment]
It hasn't.

**Comment by jeremycobert** [comment]
Is it as simple as replacing all reference in mysql.php to mysql_ to mysqli_ as Dannyuk1982 mentions ?

> Warning: mysql_connect(): Connection refused in /volume1/web/bloodbowl/lib/mysql.php on line 573 Could not connect to the MySQL server.

**Comment by rythos42** [comment]
I haven't done any research on the deprecation, and unfortunately I'm too busy to look into it. Danny's comment seems correct, as well as where he remarks that we really should be using a wrapper, with PDO under it.

If you want to take a look, I'd happily accept a pull request!

**Comment by byrnesvictim** [comment]
I'm going to close this issue as it related to the #245 PHP7 issue. Please feel free to re-open if you think this has been done in error.
