### ISSUE TITLE
Almost no translations when generating PDF roster

### ISSUE THREAD

**Issue by vanhu42** [TheNAF/naflm#177]
When generating PDF roster (tested in french and italian), almost everything is still in english.
skills are the only translated texts.

**Comment by mfranchetti** [comment]
Assume that the PDF generation function is hard coding a lot rather than using the translation file.

**Comment by byrnesvictim** [comment]
Combining with https://github.com/TheNAF/naflm/issues/210, which covers this and others in a broader way
