### ISSUE TITLE
Support new version of Blood Bowl

### ISSUE THREAD

**Issue by rythos42** [TheNAF/naflm#182]
@Shteve0 and I are working on this one. He's doing a new game data file and I'm doing a selector in the League Preferences section so leagues can choose their own version.

**Comment by rythos42** [comment]
I've done an initial commit of some work to allow commissioners to choose which core rules they use. The selector is in the League Preferences screen. There are some big caveats here!

- If the settings_LID.php file doesn't have a line for $settings['core_rules_file'], the Commissioner will be unable to change this value, no matter what they select! (the value comes from the default and is never written to their file)
- Because of how game data is loaded, there is an opportunity for some modules to fail. I had to move game data loading to AFTER the league settings file loaded in setupGlobalVars(), which moves this after module load, and there is a comment here in header.php saying some modules may depend on game data. We'll look to look into this, and possibly re-write how setupGlobalVars() loads settings_LID.php.

**Comment by ZerosGiven** [comment]
Hi Guys

I'm the Commissioner of the Leicester Blood Bowl League. We use OBBLM (pre NAF v1.0) and its the Heart of our league. I'm looking to add some of the new BB2016 rules in and wondered whats the best way? Would I need to update to the 1.0v first? I'd like to be as helpful to you guys as I can because I think its a great program and we should push it forward.

Cheers
Duncan

**Comment by rythos42** [comment]
If you weren't concerned with supporting both LRB6 and BB2016 at the same time, you would modify lib/game_data_lrb6x.php with the new stuff.

I don't know what needs changing - I let other people deal with that. :)

However, I believe the last word (in e-mail, not here) was that NAFLM will likely be going entirely to BB16 in the near future. If you were feeling lazy, you could wait for that. I don't have a timeline on that though!

**Comment by ZerosGiven** [comment]
So if I just update my system (not naf hosted) to v1.0 I can get the updated version but not the BB2016. Then when a future update comes for OBBLM (non NAF) we can have these rules as optional?

I guess I can just add the skills and stars in and just go with that, but at some point we really want to run 1.0

Cheers

**Comment by rythos42** [comment]
Oops, yeah sorry forgot to answer that question. :) You don't need to update to 1.0 in order to support BB16, as 1.0 doesn't even support it yet! You can do whatever you like!

I believe that BB16 won't be optional in NAF-hosted once it's supported, but it will be optional for non-NAF-hosted. Each host (should) be able to select their ruleset.

**Comment by williamleonard** [comment]
If you do this update, be aware that you might run into issues with any customizations that you have done.  I have had 2 to 3 people roll back the upgrade because their customized races didn't match properly.  If you have no customizations, I can update your site to NAFLM for you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ZerosGiven** [comment]
Only Customisations are the CSS and Main Page Results Boxes etc, would they be a problem with this 1.0v update?

www.leicesterbbleague.com

**Comment by williamleonard** [comment]
That isn't a problem.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ZerosGiven** [comment]
Honestly i've been putting off the update because I struggled so much to get the site looking and working the way it does and feared the new version would mess all that up. Is this view irrational or warranted? It was a VERY steep learning curve to get it the way it is lol!

**Comment by rythos42** [comment]
It's not an unwarranted fear. We changed a lot of look-related stuff in
1.0, particularly to do with the menu. If you update, there is a good
chance that some of your work will need to be re-done. I can help with that
a bit if you need (but can't do it for you :))

**Comment by williamleonard** [comment]
Personally I agree with you and unless there are things required with the update, it would be a tough decision to upgrade for me as well.  I think you will have some problems that may or may not be easy to overcome.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by rythos42** [comment]
I reverted the changes I made earlier for this.

game_data_bb16.php still exists in the system, but currently isn't being used. I think the best way to support BB16 for NAFLM is to not allow individual leagues to change their ruleset. This is a "per-host" setting, not a "per-league" setting. 

To change this, hosts will have to edit header.php line 93. Or it could be better to put this into the settings.php file for the system so it's easier to change for others.

**Comment by mrzay** [comment]
Hi @rythos42,

So I could just edit header.php and replace 
require_once('lib/game_data_lrb6.php'); 
for 
require_once('lib/game_data_bb16.php');  
in line 93 and that should work to bring it to BB16?

**Comment by rythos42** [comment]
That, and Sync Game Data in one of the Admin menus is what I'd do. But I can't promise it will work - I haven't tried it yet!

**Comment by mrzay** [comment]
In theory it works, just like modifying the lbr6 file. However, it breaks because of a translation issue for all new skills and star player created.

**Comment by FTgremlin** [comment]
Looks like we need a way to just ignore translation errors. I'm not sure how to do this.

**Comment by Shteve0** [comment]
I've updated the stars, skills and relevant translations - I think we're about ready for a patch, which I'll put out later today.  Certainly I think a ruleset selector for the install - perhaps in the core menu? - is a good idea, as to whether set race and ruleset files are loaded.

**Comment by algomu** [comment]
I hope this will be the indicated forum to ask. I Installed naflm and create teams and League/division fine but, when I tried to create a RR tournament from scheduler I get "Request Failed", I can't see nothing more. I add three teams to avoid the message, that says that minimum three teams. We are testing to use this new version and all seems to work fine but we are unable to create RR tournament. ¿There is any place to see the error?

**Comment by rythos42** [comment]
I'm afraid that for myself, I'm unable to provide support for this product anymore. :( If you've installed it, you should be able to edit the PHP and do some google searching to figure out how to get better error messages from the system. Here's a sample search I would look at:

https://www.google.com/search?q=php+debug+errors&rlz=1C1GCEU_enCA827CA827&oq=php+debug+errors

I'm sorry that I can't help more -- between the day job and the kid and the various COVID issues, I'm swamped. :(

**Comment by byrnesvictim** [comment]
Closing this as BB2016 support is fully implimented. @algomu if you are still have an problem please open a fresh issue
