### ISSUE TITLE
Adding a skill: Get TRANSLATION ERR when adding it to a character.

### ISSUE THREAD

**Issue by kirreen** [TheNAF/naflm#186]
So I tried to add a Weeping Dagger skill and give it to Gutter Runners. However, it says something like "TRANSLATION ERR ! skill/weepingdagger". Also, I tried to change the cost of a Human Catcher. Works in the Team creation but not after the team has been created.

Both of the changes were through edits of game_data.php. I resynced in the core panel afterwards, several times.

**Comment by Shteve0** [comment]
This is now added in the latest game files, and will be released in the next update.
