### ISSUE TITLE
Mobile friendly interface?

### ISSUE THREAD

**Issue by rythos42** [TheNAF/naflm#19]
Hello!

I was playing an amazing number of games on Saturday when I noticed that the interface is difficult to use for mobile phones. To see your roster or enter game information, you have to scroll, and then the label (and player name) is out of view so you can't tell what field you're typing in.

I'm also volunteering to write such an interface. Obviously, with code reviews, and any discussion/code changes, whatever the maintainers would like!

(I logged this as #706 on nicholasmr/obblm, and had a conversation with Shteve0 on Talk Fantasy Football about it, thought I'd re-log it here since here is now where I'm working!)

Thanks,
Craig

**Comment by rythos42** [comment]
I've committed an draft view-only interface suitable for mobile phones to my fork. It's a draft, I'm still working on it and plan on including functionality to:

* schedule a match
* edit the most important match details
* set new skills on players

I've attached a bunch of screen shots -- if anyone has any comments, I would welcome constructive criticism!
![login](https://cloud.githubusercontent.com/assets/937640/10089183/a53f8bb6-62d5-11e5-9938-b1c046ce6c9b.jpg)
![match details](https://cloud.githubusercontent.com/assets/937640/10089181/a53e8c8e-62d5-11e5-8566-22820f701244.jpg)
![match summary](https://cloud.githubusercontent.com/assets/937640/10089182/a53ea232-62d5-11e5-8ab5-eedf21885938.jpg)
![player details](https://cloud.githubusercontent.com/assets/937640/10089179/a53c57b6-62d5-11e5-9c67-cd44b1f99a89.jpg)
![player summary](https://cloud.githubusercontent.com/assets/937640/10089178/a53bf3a2-62d5-11e5-80b1-8e64b79f2861.jpg)

**Comment by Shteve0** [comment]
Great work on this, very much looking forward to seeing how you get on!

**Comment by rythos42** [comment]
Thanks! I'm just testing the core "Save" functionality right now. It's been a big chunk of work, and it's not quite done yet!

**Comment by mfranchetti** [comment]
What falls under 'most important match details'?
I'm just considering what are the things coaches are most likely to want to do from a mobile. My thoughts are that it will be primarily around playing a match. So:
- Schedule a match
- Record match results
- View rosters (ideally minimal info - player number, position, (name?), stats and skills, any niggles, (Total SPP?)
- Selecting skills (for when you've forgotten to do it prior to a match or when playing multiple matches in a row)

**Comment by rythos42** [comment]
The definition I'm working with is "match details that could affect the outcome of the players next game". So it includes player touchdowns, mvp, etc, as well as income and fan factor. I included score as well, because it seemed silly without it. :)

Showing niggles is a great idea that I hadn't considered!

The rest of your thoughts are mirroring my thoughts, which is great!

**Comment by Shteve0** [comment]
Also: bounty?

**Comment by rythos42** [comment]
I don't see bounty in the UI - where is it and what does it do?

**Comment by Shteve0** [comment]
I'm not sure it does anything other than assign a reward value to players. Some leagues operate a bounty system that puts a price on a certain player's head that pays out when the player is killed or forced to retire... I assume manually.

http://thenafdev.obblm.com/handler.php?type=wanted

**Comment by rythos42** [comment]
If it's ok, I may leave that for a future iteration of the mobile interface.

**Comment by Shteve0** [comment]
By all means :)

Have had a play with it. Seems to be just a text field - there's no automated reward system. Would be a nice to have at some stage.

There's a player in Default league I've added a reward to as a demo.

**Comment by rythos42** [comment]
I've got *most* of this done now, and am wondering how you'd like to handle it. A few things that come to mind:

1. I send a pull request right now, even though it isn't completely finished. It can then be deployed to the demo and checked out and commented on and all that jazz. I'd send another pull request when I was done.
2. I finish my last few items and send the pull request.

The reason you might want it early is...I'm getting married next week, and then a honeymoon...and may run low on free time to work on this for a week or two! :)

The things I still need to do: a bunch of testing, hiring players/journeymen, buying apothecaries, cheerleaders, coaches and rerolls. I've merged naflm with my fork and we don't have any overlap of changes, which is super nice. :)

**Comment by rythos42** [comment]
Despite things getting busy, I re-used a chunk of existing code to get a bunch of good functionality easily! I've attached some screenshots, which I'm considering "final from my end". Still lots of room for suggestions if anyone has any!

I'm going to do a pull request, possibly tomorrow if I don't hear any suggestions, and I hope to be able to go into some description of what I did with the code to get here.

![login](https://cloud.githubusercontent.com/assets/937640/10322459/ad8d4806-6c32-11e5-8152-85257f5b2c60.png)
![match detail - editing](https://cloud.githubusercontent.com/assets/937640/10322457/ad8d22cc-6c32-11e5-83fd-611b52b0b321.png)
![match detail - locked](https://cloud.githubusercontent.com/assets/937640/10322460/ad907a9e-6c32-11e5-8361-9ea672932e9f.png)
![match summary](https://cloud.githubusercontent.com/assets/937640/10322461/ad908750-6c32-11e5-8f3a-124e2872d9ca.png)
![team management](https://cloud.githubusercontent.com/assets/937640/10322458/ad8d2876-6c32-11e5-93a0-86e4489b8f8c.png)
![team player with new skill selection](https://cloud.githubusercontent.com/assets/937640/10322462/ad9132ae-6c32-11e5-9fbf-5d3e3e0bb8ad.png)
![team summary](https://cloud.githubusercontent.com/assets/937640/10322464/ada1fd50-6c32-11e5-9a49-76eb67d13730.png)
![schedule match](https://cloud.githubusercontent.com/assets/937640/10322463/ad9f47fe-6c32-11e5-8ff3-172072384dda.png)

**Comment by Shteve0** [comment]
Brilliant work! Apologies for not replying sooner - please do go ahead with
the pull request, can't wait to check it out!

**Comment by rythos42** [comment]
If folks are happy with this (at least, for now!), can we Close this issue?

**Comment by Shteve0** [comment]
Yep, works for me!

On Thursday, October 29, 2015, Craig Fleming <notifications@github.com>
wrote:

>
> If folks are happy with this (at least, for now!), can we Close this
issue?
>
> —
> Reply to this email directly or view it on GitHub
<https://github.com/TheNAF/naflm/issues/19#issuecomment-152036844>.
