### ISSUE TITLE
The banner doesn't show up

### ISSUE THREAD

**Issue by volaboing** [TheNAF/naflm#191]
Hi

After changing the banner.png file, (which by the way I can only find under the "images" folder), I can't get it to show up on the front. Can anybody help?

Kind regards

Ulrik

**Comment by Halfnir** [comment]
do you have an URL to show? 
does the new banner have the exact same filename (case sensitive)? 

BR, Tim.

**Comment by volaboing** [comment]
Hi Tim

The banner is named banner.png (just like that), and the URL is aafc.obblm.com. Hope you can help.

Cheers,

Urik

**Comment by jeremycobert** [comment]
http://aafc.obblm.com/images/banner.png  shows up for me so you permissions seem correct to view it

**Comment by Halfnir** [comment]
stylesheet1.css overwrites your banner from stylesheet_default.css with the default NAF banner.
you have to chage the league core theme to OBBLM default or if you want to keep the NAF theme  you'll have to remove div.banner background property from stylesheet1. You can easily simulate it in your browser by inspecting div.banner

**Comment by volaboing** [comment]
Thanks - but the problem is also, that I don't really know how to do the things you suggest. How do I change the league core theme? And also - It seems a little wierd that it should be so complicated, as the help file from NAF states, that all you should do, is change the files in the current setting. Hope you can help me.

Cheers,

Ulrik

**Comment by thefloppy1** [comment]
You have a couple of problems I can see here.

First I didn't document changing the banner as I thought this would be out
side most peoples abilities, as it is a little more than just re-naming an
image to banner.png.

You need to make sure that your banner is 150x1000px.
Once you have saved it to the correct directory make sure you flush your
cache other wise you will still see the old "OBBLM Banner"

The core theme.  can be changed from the
League Preferences Administration

page.

These are the core themes
    '0' => 'OBBLM Default',
    '1' => 'TheNAF',
    '2' => 'AUSBOWL',
    '4' => 'OBBLM Modified',
    '5' => 'CHOP!',

There are also cleanslate themes as well. But these will require a but of
work. (hmm are these in the current build)

if you do choose one of the clean slate themes and you want a custom banner
that means renaming the banner to some thing different, it is different for
each theme.

On Page 24 of the NAF OBBLM ADMIN GUIDE you will see how to change the
league preferences. and the Core theme.

cheers

**Comment by thefloppy1** [comment]
Further there are the main themes as I documented, (re my question on the
current build)

OBBLM Default – this is the theme from the Original OBBLM
TheNAF – this Red theme
AUSBOWL – a Blue theme for the Australian Ausbowl group.
OBBLM Modified – The OBBLM theme but a little darker
CHOP – A Theme for the CHOP league
Bluewhite – a Blue and white theme
Greenwhite – a Green and white theme
Iframe – a theme that uses iframes
Redblack – a red and black theme
Yellowblack – a yellow and black theme

**Comment by volaboing** [comment]
Thank you very much, floppy1. I actually had to make the picture 150x1250 px to fit the screen. On another note - do you know how to remove the text on the banner "New here? Visit the NAF ....and so on"? And I have tried removing the div.banner background property from stylesheet1, but I'm not sure I'm doing it right, because nothing happens. Can you help me, if its of no inconvenience?

Cheers

Ulrik

**Comment by thefloppy1** [comment]
You could have made the banner fit with a bit of css code to make it full
screen. it might look weird on different sized screens not.

Yes it in

\localsettings\settings_#.php

the line is

$settings['banner_subtitle'] = 'New here?  Visit theNAF.net/Leagues for
more information';

**Comment by volaboing** [comment]
Thanks again. Sorry to have bothered you.

Kind regards

Ulrik

**Comment by Shteve0** [comment]
The following code added to your league css settings in the admin panel will remove the css banner and replace it with the image file packaged with the default obblm (or any image you overwrite it with in the back end).  I'll update the default skin in the next update, thanks for the heads up.

```
/* Banner */
div.banner {
    height: 150px;
    background-image: url(../images/banner.png); /* 150x1000px */
    background-repeat: no-repeat;
    background-position: top left;
}

f1 {display:none}
f2 {display:none}
```
