### ISSUE TITLE
Can't change the banner in NAF-theme

### ISSUE THREAD

**Issue by volaboing** [TheNAF/naflm#195]
Please help. 

I can't seem to be able to change the banner in the NAF-theme. I like the colors, and would like to keep it, but the banner doesn't change when I upload it.

Kind regards

Ulrik

**Comment by thefloppy1** [comment]
Make sure you flush your cache on your browser once it is uploaded.

The NAF theme

The banner should be called logo.png
The problem is that it might cause some issues as there are quite a few
extra pieces of code in the CSS that do things.

What is the URL of your League.

cheers
Floppy

**Comment by volaboing** [comment]
The URL is http://aafc.obblm.com/

**Comment by thefloppy1** [comment]
This is the screen shot of what I see

[image: Inline image 3]
This looks fine to me.

**Comment by Halfnir** [comment]
If uploaded changes are not visible in your browser, always try to refresh your browser cache as a first measure. Had a similar case yesterday where an updated stylesheet on obblm.com was not recognised by the browser until a hard refresh.

**Comment by volaboing** [comment]
Thanks, floppy. I figured it out, just after you wrote. Thats why it looks good. Thanks for all your help. and just for the hell of it - how on earth do I change the names of the players.

cheers

**Comment by thefloppy1** [comment]
We have been testing a new name and number changing system. It will be out
with the next release I hope.
