### ISSUE TITLE
How do I buy inducements for a match?

### ISSUE THREAD

**Issue by kirreen** [TheNAF/naflm#196]
Can't find where to buy inducements, I can only find the "try out inducements" on the team page.

**Comment by jeremycobert** [comment]
here, I created a video on how to add inducement
https://youtu.be/X7FrztGtzkw

**Comment by kirreen** [comment]
Is this really correct and not just for testing you TV with inducements? It doesn't take any money from the team and it doesn't save anything.

**Comment by jeremycobert** [comment]
Are you adding the inducement to your team prior to a match ? If so, this save when you click on the inducement and then it changes your team value.

**Comment by kirreen** [comment]
Well, it changes the team value on the inducements screen and the PDF it can generate, but isn't it supposed to show up in a scheduled match afterwards?

**Comment by thefloppy1** [comment]
Inducements are part of prematch. Done before first dice because your
opponent might add gold to get inducements as well raising your inducements
level

**Comment by kirreen** [comment]
Is there like a prematch menu in OBBLM? How do I spend gold from my treasury to get petty cash to buy inducements?

**Comment by jeremycobert** [comment]
Oh I see, it does not look like you can setup all inducements pre match and have it added to the match print out.

**Comment by thefloppy1** [comment]
That is taken care of in the match report.

On 28 Jan. 2017 1:11 am, "kirreen" <notifications@github.com> wrote:

So how do I remove money from teams that want to buy inducements?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/TheNAF/naflm/issues/196#issuecomment-275673484>, or mute
the thread

**Comment by kirreen** [comment]
Thanks! Delta-treasury seems relevant :)
