### ISSUE TITLE
Install.php - error (bank_threshold) (T_STRING)

### ISSUE THREAD

**Issue by Akkim** [TheNAF/naflm#199]
Parse error: syntax error, unexpected 'bank_threshold' (T_STRING) in M:\wamp64\www\settings.php on line 30

________________ Relevant information from settings.php ___________________________

$settings['site_name'] = 'Akkim\'s BloodBowl 2016 League';                         // Site name.
$settings['default_visitor_league'] = 1;                            // ID of default league to show on front page when not logged in OR coach has not selected a home league.
$settings['default_leagues'] = array();                             // When creating a coach the coach will automatically become a regular coach in leagues with these IDs.
$settings['hide_ES_extensions'] = false;                            // Default is false. Hides ES (Extra Stats) tables and ES references.
$settings['league_coordinator_email'] = 'micah.imparato@gmail.com;    // Sent "Request League" e-mails

$rules['bank_threshold'] = '0'; // Default is 0 (banking rule disabled). Amount of team treasury in kilos (k) above which it will count towards the team value (TV). NOTE: 1) This feature is not yet available on a per-league basis, it works across all leagues! 2) When changing this value run "Re-install DB back-end procedures and functions" under "DB maintenance" from the "Admin -> Core panel" menu.
$rules['force_IR'] = false; // Default is false. Setting this to true will remove the ability of selecting 0-0 as 2D6 injury rolls (IR) in match reports (of all leagues).

/*
    Game data - additional races
        OBBLM uses LRB6 by default.
        In addition you can include the custom races below. Simply change the keywords "false" to "true" (without apostrophes).
*/

$settings['custom_races'] = array(
    'Bretonnia'         => false,
    'Daemons of khorne' => false,
    'Apes of wrath'     => false,
);

**Comment by Akkim** [comment]
This is connected to the "v1.0" release as posted at TheNAF - using the MASTER branch here, I did not encounter the error, but I DID get the notice:

Notice: Undefined variable: argv in M:\wamp64\www\install.php on line 30

**Comment by Akkim** [comment]
Ignoring that message, I did the setupDB, removed install.php and proceeded to the website and found random SQL issues through the default state...


![obblm-mssql-issues](https://cloud.githubusercontent.com/assets/900839/22550733/6e19198c-e91f-11e6-9eb2-86c6a4f48d45.png)
![obblm-mssql-issues-02](https://cloud.githubusercontent.com/assets/900839/22550734/6e23597e-e91f-11e6-86d2-81105f779704.png)

**Comment by thefloppy1** [comment]
I have a couple of questions.

1. where is this hosted, by the NAF or by a 3rd party host?
2. MYSQL version
3. PHP version

I would like to run up a new install with your versions of these to test
for the problem.

cheers

**Comment by Akkim** [comment]
Hosted on my own platform (Windows 2012 R2) running WAMP

**Comment by thefloppy1** [comment]
ok.

php version if you know it?
mysql if you know it?

cheers

**Comment by Akkim** [comment]
I updated the comment to include that info ;)

**Comment by thefloppy1** [comment]
ok as soon as you said 2012R2 I sort of expected it was 

PHP:7.0.10 MySQL:5.7.14  

I have started cycling up a VM now with 2012 on it, It was tested with php 5.3 and Mysql 5
give me 30 minutes or so.
I expect I know what the problem is, but I will get back to you.

**Comment by Akkim** [comment]
Yeah.. I came here originally from the NAF v1.0 posting, but that build was a little messed up... so I grabbed the master from here and had a little better luck, but it's still not quite clean ... I was looking to use OBBLM for a BB2016 league :)

**Comment by williamleonard** [comment]
FYI - For PHP 7, It won't work.  Mysql functions are removed.  I setup a test installation with PHP 7 and created a wrapper library and was able to get everything working except the class_statsgraph.php and fpdf.php errors.  They use a thirdparty class that doesn't work with PHP 7.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by thefloppy1** [comment]
ok tested.

problem is the php library's.  I didn't think that it would work with php7 and that looks to be the case. is there anyway you can roll back to php5.1 to 5.6?

This will take a fair bit of work to bring php code inline with 7.x and will break all 5.x installs.

**Comment by Akkim** [comment]
I did a bit deeper of a dig, the active PHP version is 5.6.25.

--Micah

**Comment by thefloppy1** [comment]
I would recommend that rolling it back to 5.1 or 5.3 might be best.

**Comment by Akkim** [comment]
Going to see if I can't get 5.3.29 and party like it's 2014... ;)

**Comment by thefloppy1** [comment]
This is not a new piece of software, it was inherited by a new team and and
we all have been slowly upgrading it.  there are still things written in
very old code.

**Comment by Akkim** [comment]
I'm aware, I had been involved with OBBLM way back when Cyanide kicked out their first BB product way back when and worked on the Cyanide module.  It's just one of those frustrating things about php environments, unfortunately :(

I'm a bit confused between the NAF posting of v1.0 and the Master fork here, which seems to have reverted back some of the stuff from there?

**Comment by thefloppy1** [comment]
Masterfork has current working files.  The Naf install is the stable.

**Comment by williamleonard** [comment]
5.6 works fine.  I wouldn't recommend it rather than anything else since all of the development is tested in 5.6.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Akkim** [comment]
My current install is 5.6.25 and has the php errors as in the screenshots... it simply might be missing files?

**Comment by thefloppy1** [comment]
Can you surprises the warnings.

**Comment by Akkim** [comment]
http://66.203.73.171/

Warning: mysql_fetch_object(): supplied argument is not a valid MySQL result resource in M:\wamp64\www\lib\class_objevent.php on line 74
 --- I am assuming that this is just not handling the failure of a SQL query well?
---- content of line 74 of class_objevent.php...
 ---         while ($row = mysql_fetch_object($result)) { 

Warning: fopen(M:\wamp64\www\css/league_override_1.css): failed to open stream: No such file or directory in M:\wamp64\www\lib\class_filemanager.php on line 42
 --- I don't see that file (league_override_1.css)

I mean it's just suggesting to me missing content in the download .zip from the master fork?

**Comment by thefloppy1** [comment]
That is created in the "League Preference Administration"

right down the bottom

League CSS
*(careful if you don't know CSS)*
You may need to clear cache after editing.

Then you can add custom CSS with out having to edit any css files.

mine has  a heap of stuff to make it responsive and full width etc.

**Comment by Akkim** [comment]
Okay.. so until I created a Division and a Tournament, I was unable to finish that League Administration thing to clear the errors out - now that's successfully updated the record and it's behaving nicer.

I still get that ugly MySQL blurb on the front page - I'm assuming this is due to a lack of any player deaths yet... how can that gracefully return zero results?

**Comment by thefloppy1** [comment]
localsettings/settings_#.php
where # is the league ID.

array(
        'id'        => 6, # Node ID
        'box_ID'    => 8,
        // Please note: 'type' may be either one of: 'league', 'division'
or 'tournament'
        'type'      => 'league', # This sets the node to be a tournament.
I.e. this will make an event box for the tournament with ID = 1
        'title'     => 'latest dead', # Table title
        'content'   => 'dead', # Event type
        'length'    => 5, # Number of entries in table
    ),

make sure the 'id' => your league ID.

It should look something like what I ahve there. this is all part of the :

/*********************
 *   Front page: event boxes
 *********************/

$settings['fp_events'] = array(
    /*
        Event boxes can show for any league, division or tournament the
following:
            dead        - recent dead players
            sold        - recent sold players
            hired       - recent hired players
            skills      - recent player skill picks
    */

**Comment by thefloppy1** [comment]
any other problems I will look at while at work.
cheers

**Comment by Akkim** [comment]
If you browse to my site you'll see the MySQL failure - I'm still not sure why it chokes on the Death table, but not the Skills table.

From settings_1.php

        'id'        => $get_lid, # Node ID
        'box_ID'    => 5,
        // Please note: 'type' may be either one of: 'league', 'division' or 'tournament'
        'type'      => 'league', # This sets the node to be a tournament. I.e. this will make an event box for the tournament with ID = 1
        'title'     => 'Latest Dead Players (League)', # Table title
        'content'   => 'dead', # Event type
        'length'    => 5, # Number of entries in table
    ),

array(
        'id'        => $get_lid, # Node ID
        'box_ID'    => 6,
        // Please note: 'type' may be either one of: 'league', 'division' or 'tournament'
        'type'      => 'league', # This sets the node to be a tournament. I.e. this will make an event box for the tournament with ID = 1
        'title'     => 'Latest Skills (League)', # Table title
        'content'   => 'skills', # Event type
        'length'    => 5, # Number of entries in table
    ),

**Comment by Akkim** [comment]
Actually, the SQL warning might be tied to the Skills display so I wonder about the Skills part of the class_objevent.php code.. 

    case self::T_PLAYER_SKILLS:
        $query = "SELECT player_id AS 'pid', game_data_skills.skill_id AS 'skill_id', game_data_skills.cat AS 'cat', game_data_skills.name AS 'skill_name', CONCAT(game_data_skills.name,' (',game_data_skills.cat,')') AS 'skill', $_COMMON_COLS__T_PLAYER FROM players, mv_players, players_skills, game_data_skills WHERE 
            players.player_id = mv_players.f_pid AND 
            mv_players.f_pid = players_skills.f_pid AND
            players_skills.f_skill_id = game_data_skills.skill_id AND 
            ".$mv_keys[$node]." = $node_id 
        GROUP BY player_id, f_skill_id ORDER BY players_skills.id DESC LIMIT $N";
        $result = mysql_query($query);
        while ($row = mysql_fetch_object($result)) {
            $events[] = $row;
        }
        break;

**Comment by thefloppy1** [comment]
create a team and see if it cleans it up.

I personally hard set my node ID's.  but the with the current build i need
to really sit down and test everything again.

**Comment by Akkim** [comment]
I did create my team and everything.  There's a few more blocks that are acting up, but again - it could be the fact that it's basically a virgin database... but then again, that's a valid test case in and of itself :)

**Comment by thefloppy1** [comment]
I tested the naf version with all cases I could think of. I have never had
these, I finish up here at work shortly, I will cycle up a couple of VM's
and install Windows server I will exclude as this could be a problem, so I
want to isolate that and do tests on just a raw nix db clean install.

**Comment by Akkim** [comment]
I have next to nothing in the database other than the initial stuff - I am perfectly happy with blowing everything away to be a clean test case as well - I am using the x64 build of WAMP, perhaps that's part of the issue?

**Comment by thefloppy1** [comment]
I think that it might be part of the issue.
I just downloaded and installed obblm on my test server

http://sticentz.com/naflm-master/index.php?section=main

the only thing i have setup is the league name.

Did you syncall () in the corepanel?

**Comment by thefloppy1** [comment]
I do need to do some more testing while not at working being paid to do
testing today...

**Comment by Akkim** [comment]
I can run the 3 database elements fine... but the SyncAll fails!

I understand, but I appreciate it.  I may try removing 64-bit and installing 32-bit and seeing how it goes.

**Comment by Akkim** [comment]
WAMP 32-bit, all 32-bit VC++ runtimes installed... fresh master.zip installed... league/division/tournament created..  still seeing same issues, still seeing syncall() failures.

**Comment by thefloppy1** [comment]
can I log in using root?

**Comment by Akkim** [comment]
I have changed it from the defaults, hang on :)

**Comment by Akkim** [comment]
Okay.. back to root/root

**Comment by thefloppy1** [comment]
Question,
What permissions did you give the root database user?

cheers

**Comment by Akkim** [comment]
I created a separate user and db for OBBLM.  

I had that user setup with all global privileges and it didn't change things.  As such I have put it back to global "Create Routines" and on the OBBLM database, all privileges.

**Comment by thefloppy1** [comment]
this is how they should be setup

Setup Database
It is important that we setup the database before we do anything else. As
stated previously it is important that the database user be granted the
correct permissions.
If you are using a webhost that has a MySQL wizard this step is very quick.
Please note down the database name and user name, and password when you
create the database.
 CREATE PROCEDURE
 CREATE FUNCTION
 or CREATE ROUTINE (contains both CREATE PROCEDURE and CREATE FUNCTION).

**Comment by Akkim** [comment]
![image](https://cloud.githubusercontent.com/assets/900839/22578837/af005b52-e999-11e6-92e1-ccad24f9305a.png)

As you can see the User Bloodbowl has all necessary permissions.  Originally it was setup with all permissions on a global level as well.

**Comment by Akkim** [comment]
Dropped the Bloodbowl DB, re-created it.  Re-did the install.php.. then logged in the first time.. SQL did all the updates including installing all it's procedures :/

![image](https://cloud.githubusercontent.com/assets/900839/22579279/c73bfebc-e99c-11e6-8e87-070102d00d4d.png)

**Comment by Akkim** [comment]
I'm going to close this issue as being the result of using WAMPSERVER x64 - I'm going to remove the other comments and open a separate issue to track this behavior with the proper bits as we have moved on to other errors out of a default install running WAMPSERVER x86 and valid versions of PHP/MySQL, etc.

**Comment by mfranchetti** [comment]
Looking at the original error, it's just a parsing issue. You haven't closed the inverted commas around the email address on the previous line.
You also have a parsing issue on the Site name as you've used an inverted comma as part of the string. You should either enclose the sting in double inverted commas or escape the inverted comma. Examples below:
$settings['site_name'] = "Akkim's BloodBowl 2016 League"; // Site name.
$settings['site_name'] = 'Akkim\'s BloodBowl 2016 League'; // Site name.

Not sure if these issues would have impacted the install and caused the errors you were seeing, but I'd rectify them first and try a fresh install.
I run PHP 5.6.31 without issue.
