### ISSUE TITLE
Red Background

### ISSUE THREAD

**Issue by rythos42** [TheNAF/naflm#20]
I find the red background with white text difficult to read. It looks great in the header, but once it comes to the functional areas, it's a little too much.

Unfortunately, I have no graphic design background so I don't have a colour solution in mind, but the off-grey with black of this design (http://thenaf.obblm.com/) seemed ok to me.

**Comment by Shteve0** [comment]
I'm working on different skins - it's a tricky one as I've inherited the design (member.thenaf.net) that we're replicating here - with a new NAF website in the pipeline, this issue will be addressed.

**Comment by rythos42** [comment]
I had been wondering where the red came from, but didn't want to step on any toes. >.>

The colours of member.thenaf.net aren't great, but they don't suffer as much because of the white/off-white backgrounds they use. The right-side menu is bad. I find I have to strain to read anything on it, which isn't conducive to users wanting to navigate the site! 

I've attached a screenshot, and have put yellow boxes around the areas that are hard to read. The bottom links in Recent games are "ok" because they are big, but I have to strain. The +/- links I can barely see because they are so small and blend in!

If the red background is here to stay, I think we either need to add another box around the important items, with a white or off-white background. Or we need to change link colours whenever they are on top of red (possibly both in some cases)

![matches screen](https://cloud.githubusercontent.com/assets/937640/10232383/4e5b4ebc-683d-11e5-8b63-e437607b9b28.jpg)

**Comment by rythos42** [comment]
I totally skipped over the sentence about new NAF website!

If there's a new site in the works, can we change our design to mimic IT instead of trying to mimic the existing site? Design for the future we want instead of the present we have? :) Just a thought.

**Comment by rythos42** [comment]
Here's another page that hasn't gone well in the skin change.

Is there a possibility we could return to either white or light grey backgrounds, and use red headers to keep the colour scheme "similar but not identical" to the NAF page?

![another red](https://cloud.githubusercontent.com/assets/937640/10373242/13c2779e-6da1-11e5-9bba-0d73d6b3da1d.png)

**Comment by Shteve0** [comment]
Yep, not ignoring this. Been banging my head against the disappearing
announcements issue.

That particular case you've attached here is unrelated to the hyperlink
problem (where I have one colour for use on all backgrounds) so I can fix
it quickly. The hyperlink issue I might need to split out into two colours,
one for dark and one for light, but then potentially that's a huge change.
Still mulling on it.

**Comment by rythos42** [comment]
Sorry - just wanted to note down pages where it was particularly noticeable so we could check them after a fix is determined.

**Comment by rythos42** [comment]
It has been decided to leave this for now. League commissioners can adjust their own CSS, and the style is planned to be changed again in the near future anyway.
