### ISSUE TITLE
New Catcher Cost - Not Working For Old Teams

### ISSUE THREAD

**Issue by ZerosGiven** [TheNAF/naflm#201]
Once the update is done, any team that was created before the patch but has NOT yet played a game has an issue where the new costs are not active. Got around it buy adjusting Gold.

Small issue but worth investigating.

**Comment by mfranchetti** [comment]
This should be resolved by doing a SyncAll() from the Core Panel. That should have been done as part of the patch, not sure if it's in the instructions or not.
