### ISSUE TITLE
Apes of Wrath

### ISSUE THREAD

**Issue by legionsrealm** [TheNAF/naflm#202]
I turned the team on in the settings but when the coach goes to build a team, the players are missing. What can I do to resolve this? League OBBLM is hosted at Mercury VPS. Leonard referred me here.

**Comment by williamleonard** [comment]
You would run a sync all from the admin menu.  I didn’t think of that when you asked me earlier😊

**Comment by legionsrealm** [comment]
I think I tried that but ill do it again and post a reply.

**Comment by legionsrealm** [comment]
Nope. When the team is created, it doesn't apply the race which doesnt allow for the players to be selected.

**Comment by fejwe** [comment]
Having the same/similar issue. I turned on the teams in the settings.php file within local settings, then ran the sync all, but the teams' names don't appear in the team creation dropdown.

**Comment by mfranchetti** [comment]
Is this issue still ongoing? Can you provide a link to your site?

**Comment by byrnesvictim** [comment]
Closing this due age and we now have a note in the settings file that all Sync tasks are required when changing these values.
