### ISSUE TITLE
DE Assassin icon

### ISSUE THREAD

**Issue by duke-68** [TheNAF/naflm#209]
Hello, I've found a very small and easy-to-resolve bug.
The icon for the DE assassin is wrongly referenced in game_data.php line 249 to 'delineman1', its value should be 'deassassin1'
Best regards

**Comment by mfranchetti** [comment]
High Priority as it's a quick fix.

**Comment by kossy** [comment]
Submitted pull request #254 which fixes this.

**Comment by byrnesvictim** [comment]
Fixed in #278
