### ISSUE TITLE
Request: allow a picture to be one of the "boxes"

### ISSUE THREAD

**Issue by sann0638** [TheNAF/naflm#21]
One of the leagues in NAF OBBLM has a sponsor, so would like a picture to appear on the right hand side (or in the league description).

**Comment by williamleonard** [comment]
Put in a screen shot of what you want, though if it just needs to be in the description, you can add it there with html tags.

**Comment by Shteve0** [comment]
Does the welcome message field of the leaguepref table allow for html? If
so can we add a restriction to the width of the image, a check on save and
a warning message if failed?

**Comment by Shteve0** [comment]
Since the introduction of custom css to the leagueprefs this is possible.
