### ISSUE TITLE
Fatal error whith TeamCreator

### ISSUE THREAD

**Issue by oddclot** [TheNAF/naflm#211]
Hi, I have translated every race and player in the Game Datas (I suppose this does not matter but I list it here cause is the only modification I made). Everything is fine and no errors have been reported in existing teams.

The thing is when any Coach tries to create a New Team (even me as admin), we all get this message 
array_to_js - FATAL ERROR: Unknown Datatype for "races[15]["players"][5]["ma"]"

I checked race 15 in case it has a minor error but this is not the case. Then I disabled TeamCreator in settings_modules, but then when we try to create new teams we get a blank page.

The only way I found to create new teams is to use a direct link like 
http://OBBLM_DOMAIN_HERE.com/index.php?section=objhandler&type=1&obj=3&obj_id=COACH_ID_HERE&subsec=newteam

Have you any idea about what is wrong with TeamCreator in our site?

**Comment by Shteve0** [comment]
Have you got the teamcreator module activated?

**Comment by Shteve0** [comment]
Hi, this has been open for a while without reply, and does not appear to be a replicated issue for others.  As such I'm closing.  If your problem persists please use the new service desk at http://theendzone.co/groups2/89-obblm.html
