### ISSUE TITLE
Can't schedule new playoff matches in existing FFA tournament.

### ISSUE THREAD

**Issue by EvilCheesypoof** [TheNAF/naflm#216]
I'm using the NAF hosted OBBLM and it gives me an error saying that two teams from different divisions can't play each other, but it doesn't make any sense since I disabled division ties, they played each other in the same tournament already, and they're in the same division!

How can I fix this?

**Comment by Shteve0** [comment]
Hi, the github is for active development and bug fixes.  Please direct support requests to http://theendzone.co/groups2/89-obblm

Cheers :)
