### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by Hjelmen** [TheNAF/naflm#220]
Hi all. 

I'm doing a fresh install of NAFLM, and my provider has PHP 7.0.21, which is seemingly not compatible with NAFLM. When running the install.php:

![image](https://user-images.githubusercontent.com/29941906/29001496-97530c28-7a8c-11e7-81e8-7702d1665c31.png)

I would imagine that this is because NAFLM still uses mysql functions, which have been removed in PHP 7

I can update the functions to use the appropriate mysqli functions, if that is the full extent of the error, but  can't find the validation that stops me from running install.

Any suggestions as how to get this running? Or any ideas on when might NAFLM be updated to be compatible with PHP 7? 

Thank you :)

**Comment by snotlingorc** [comment]
The issue is with jpgraph, not php7.    In modules/statsgraph/jpgraph, you would need to update it.  with a later version. http://jpgraph.net/download/

**Comment by williamleonard** [comment]
I suggest you have you host set the PHP version back to a supported version.  It is easy enough to do.  If they are not able to, contact me, I probably host 90% of the OBBLM and NAFLM sites out there.

**Comment by Hjelmen** [comment]
@snotlingorc: Thank you. I'll give that a try.
@williamleonard: I might set it back to an older version, but my host has flagged that that will only be a short-term workaround, as they will not support older php-versions from the beginning of 2018. So I'd rather just have it fixed, than rely on a temporary solution, which I'll then forget all about, and then have the same problem later.

Thank you both for the replies! I'll try updating jgraph, and see what happens.
