### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by dalanthalar** [TheNAF/naflm#222]
Hi, somebody know how can i fix this warnings and notice.
Notice: Undefined index: Bretonnia in /srv/disk13/2201587/www/lmbb.eu.pn/header.php on line 94

Warning: Cannot modify header information - headers already sent by (output started at /srv/disk13/2201587/www/lmbb.eu.pn/header.php:94) in /srv/disk13/2201587/www/lmbb.eu.pn/lib/class_coach.php on line 543

Warning: Cannot modify header information - headers already sent by (output started at /srv/disk13/2201587/www/lmbb.eu.pn/header.php:94) in /srv/disk13/2201587/www/lmbb.eu.pn/lib/class_coach.php on line 544

Thanks

**Comment by Shteve0** [comment]
Sounds like you have a space at the end of one of your files mate. Check
there's nothing after ?> in the files it calls out, for starters?

**Comment by williamleonard** [comment]
This is like the issue for SWWG.  They added a custom bret team in the past.  To resolve it, they had to rename it all in the database I believe.  I sent an email to the commissioner asking him to chime in.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dalanthalar** [comment]
Hi, I found the error in the file settings.php is miss written in the line 34 "Brettonia" and is written "Bretonnia"in the header.php file line 94. I copy this last in settings and fixed, thanks for your comment.
