### ISSUE TITLE
Leagues not displaying for me when I log in

### ISSUE THREAD

**Issue by epallis** [TheNAF/naflm#234]
Good day, 

I had the "admin" of a new league(Goblin Standard Blood Bowl(Westminster, CO)) I am joining set up an account for me(epallis).  For whatever reason, when I am logged in, I am never able to select a league from any of the dropdown menus.  Therefore am never able to create a new team.

Do I have some permissions set incorrectly someplace.  Could someone set my default league to Goblin Standard Blood Bowl?

Thanks!
-Ed

**Comment by mfranchetti** [comment]
Hi, it's an issue with your accoutn setup, you haven't been allocated to the league. I've corrected it and you should be good now.
