### ISSUE TITLE
How can I reset a team

### ISSUE THREAD

**Issue by chotesir** [TheNAF/naflm#238]
Hi. I've recently started a league, and we're using OBBLM. 

Is there any way to reset a team to their original roster, once we've played some games?

**Comment by chotesir** [comment]
I've to do it manually? creating the new players? Or....

**Comment by williamleonard** [comment]
You should create a new team.  Deleting a team would invalidate all matches and data that the team played.

**Comment by chotesir** [comment]
So, I create a New team, and, then? Sorry, I've just started on using the program

**Comment by Halfnir** [comment]
Then you use the new team instead of the old one. 
If the old one has still outstanding games in a round robin schedule, you have to remove those games manually (admin) and schedule the games with the new team accordingly.

**Comment by chotesir** [comment]
Ok, thanks a lot ;)
