### ISSUE TITLE
JpGraph error 13

### ISSUE THREAD

**Issue by jamendog** [TheNAF/naflm#239]
I am trying to install OBBLM, and I am getting error JpGraph error 13, when loading install.php.

My MySQL is version 7.0.27

**Comment by williamleonard** [comment]
Your PHP version is probably too high.  If your host doesn’t allow you to choose a different version, you can check out my hosting, https://www.mercuryvps.com.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jamendog** [comment]
Thanks mate.
I contacted my host, and they advised me to temporary  downgrade my site to PHP 5.6, by adding this line to my .htaccess file:
AddType application/x-httpd-php-old .php

After installation, remove the line again

**Comment by williamleonard** [comment]
You will keep it  5.6.

Sent from my Windows 10 phone

________________________________
