### ISSUE TITLE
Request: Match reports need to allow negative change in treasury

### ISSUE THREAD

**Issue by rythos42** [TheNAF/naflm#24]
Spiraling Expenses and rolling a 1, it can happen!

**Comment by Shteve0** [comment]
Also when you've spent cash on inducements.

**Comment by Shteve0** [comment]
I think I've seen a fix for this somewhere...

**Comment by Shteve0** [comment]
http://www.talkfantasyfootball.org/viewtopic.php?f=29&t=41048

**Comment by rythos42** [comment]
I've got a fix for this, but didn't realize I couldn't do another pull request until the first one is merged.

**Comment by rythos42** [comment]
Actually, it looks like by doing the pull request, then me committing again, that pull request automatically includes the treasury fix. I would have preferred separation, but...I don't get it!

This issue should be fixed in the next deployment. :)

**Comment by Shteve0** [comment]
Where did we leave this?

**Comment by rythos42** [comment]
I implemented the fix mentioned in that talkfantasyfootball link, and I think it got merged in with one of my pull requests.

**Comment by Shteve0** [comment]
Yep, looks great - nice one :)
