### ISSUE TITLE
Blank Screen after install

### ISSUE THREAD

**Issue by oj4lif3** [TheNAF/naflm#240]
I have a clean install on my laptop of NAFLM. Install went smoothly but when I go to view index.php for the first time after install, its blank. After inserting many php echo prompts in the php code, I narrowed the issue down to line 36 of the /lib/class_translations.php file. 

$this->registerTranslationFile(self::main, 'lang/translations.xml');

Usually a blank screen means there is a missing semi-colon or something like that in php but I dont see any issues with the code. Please help as I would like to setup a site on my local machine before actually having one hosted. Thanks.

**Comment by williamleonard** [comment]
Enable display_errors

Sent from my Windows 10 phone

**Comment by oj4lif3** [comment]
Okay. I have enabled display_errors.

Fatal error: Class 'DOMDocument' not found in /var/www/html/naflm/lib/class_translations.php on line 49

**Comment by oj4lif3** [comment]
Issue fixed after installing php5.6-xml
