### ISSUE TITLE
Commish's get immediately logged out, cannot do anything

### ISSUE THREAD

**Issue by oj4lif3** [TheNAF/naflm#242]
Hi, we have been using the naflm now for a season and love it. However, after following the guide -> http://theendzone.co/blog/2017-obblm-patch-to-dz2.html

We are now having problems with anyone who has sys admin access. Normal coaches can log in fine. However when a sys admin logs in , all the menu items are there and when you click on another page, it immediately logs you out. An example page would be trying to access Admin->OBBLM Core Panel, and I am getting the "Please login." message and the "admin" menu items are gone , and we are logged out. Has this occurred before? (I have scoured the other issues and cant find anything) Any help would be awesome!

**Comment by oj4lif3** [comment]
Change that, normal coaches cant schedule matches or anything as well. Its really odd.

**Comment by mfranchetti** [comment]
This sounds like something went wrong with the patch process rather than an OBBLM bug.
Raise it in the [League Discussions](https://member.thenaf.net/index.php?name=PNphpBB2&file=viewforum&f=24&sid=7aefd8f8f207647e9e6e723b42afd749) on the NAF forum and I'll see if I can help.
