### ISSUE TITLE
Request: Match scheduler: drop down menus and to only allow from that specific tournament

### ISSUE THREAD

**Issue by rythos42** [TheNAF/naflm#25]
When scheduling a match, players and commissioners need to be able to spell or exactly remember their opponents team name.

I think a mixed "drop down" and "autocorrect" widget would be more functional, letting people see a list and select, or type, as they desire.

As well, this drop-down should only show people from the current tournament. (league commissioner requested this one, I haven't looked at it or seen the functionality)

**Comment by williamleonard** [comment]
This ability does already exist at least for other parts of OBBLM.  You should be able to reuse the same thing.  It is AJAX autocomplete or something like that.






Sent from Windows Mail





From: Shteve0
Sent: ‎Thursday‎, ‎October‎ ‎8‎, ‎2015 ‎12‎:‎47‎ ‎PM
To: TheNAF/naflm





When scheduling a match, players and commissioners need to be able to spell or exactly remember their opponents team name.

I think a mixed "drop down" and "autocorrect" widget would be more functional, letting people see a list and select, or type, as they desire.

As well, this drop-down should only show people from the current tournament. (league commissioner requested this one, I haven't looked at it or seen the functionality)

**Comment by rythos42** [comment]
Odd that I missed this. I fixed this issue a while back - it was caused by me making changes. :)
