### ISSUE TITLE
New stars not working

### ISSUE THREAD

**Issue by kavinay** [TheNAF/naflm#250]
When you try to add a BB2016 new star via the inducement interface, you get an "array" result for that star's stats and skills. Also, nothing shows up when you render the PDF.

It seem like something after line 2156 ub  game_data_BB2016,php is breaking the parsing of the star array. The swift twins do trigger the second star to be added to the inducement sheet, but again, no info is retrieved.

Any thoughts on what to look at for the fix? Would one bad star entry break it?
![obblm-newstars-capture](https://user-images.githubusercontent.com/290346/40394947-9d74dadc-5dda-11e8-8940-32ead8aa955d.PNG)

**Comment by byrnesvictim** [comment]
Try your Admin - > OBBLM core panel functions, once all of them are run the stars details should populate

**Comment by byrnesvictim** [comment]
I'm closing this issue as I believe it has been resolved with the Core Functions
