### ISSUE TITLE
mysql_fetch_object() issue After server change

### ISSUE THREAD

**Issue by mephillicus** [TheNAF/naflm#256]
In logout mode and Global commissioner login I nave this issue in some pages

Warning: mysql_fetch_object(): supplied argument is not a valid MySQL result resource in /home/mhd-01/www.xxxxxxxx.xx/htdocs/bababowl/lib/class_objevent.php on line 74

If i check "Display coach access levels" of Regular Coach on Local Access i nave this error

Warning: mysql_fetch_object(): supplied argument is not a valid MySQL result resource in /home/mhd-01/www.xxxxxxxx.xx/htdocs/bababowl/lib/class_coach.php on line 444
None 

Every regular coach has errors on every page (Always on mysql_fetch_object()) There were no such errors on the old server and Global has full functionality.

Server with PHP 5.6 and last version of the Naf obblm

Thanks!

**Comment by pollyste77** [comment]
I had same typer error in our league and disapper select standings

**Comment by snotlingorc** [comment]
What version of mysql are you running?   if 8, most likely it is related to this : https://dev.mysql.com/worklog/task/?id=8693

**Comment by pollyste77** [comment]
yes i use 8


Il giorno sab 25 lug 2020 alle ore 00:32 Snotling <notifications@github.com>
ha scritto:

**Comment by williamleonard** [comment]
You may know but I have seen a lot of people jumping the gun on upgrades.

MySQL 5.7 has an end of life of October 21, 2023.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by pollyste77** [comment]
I passed from 6.1 to 8
Polly

Il giorno lun 27 lug 2020 alle ore 14:32 williamleonard <
notifications@github.com> ha scritto:
