### ISSUE TITLE
Request: Commissioner able to set the league for stats on the main page

### ISSUE THREAD

**Issue by rythos42** [TheNAF/naflm#27]
He wants to be able to set what League these statistics come from:

![give league commissioner ability to select league for these stats](https://cloud.githubusercontent.com/assets/937640/10373346/bac258b6-6da1-11e5-86dd-5c7d913802b6.jpg)

**Comment by Shteve0** [comment]
Yep, that's in the new League Preferences Administration doubleskulls
module - just waiting for a deploy from Vanguard and I'll look at the
localsettings file to see why it's not resolving

**Comment by rythos42** [comment]
Awesome!

**Comment by Shteve0** [comment]
This should now be up and running for him if you ask him to try it out?  On the dev site, not the full one yet.

http://thenafdev.obblm.com

**Comment by rythos42** [comment]
I pointed him here and will let you know!

**Comment by Shteve0** [comment]
Will reopen if there are future issues, but to the level of my understanding of the issue this is fully resolved in the leagueprefs module changes
