### ISSUE TITLE
Link to wiki is dead/moved

### ISSUE THREAD

**Issue by jonaslepsoy** [TheNAF/naflm#272]
https://github.com/TheNAF/naflm/blob/ebef870c910e3a18a769b29bcc0c8e2c0a972e0b/help.html#L6

This link returns a 404. The wiki seems to have been moved to [https://github.com/nicholasmr/obblm/wiki](https://github.com/nicholasmr/obblm/wiki)

**Comment by byrnesvictim** [comment]
Thanks, resolved in the latest pull. We are now working on a NAFLM wiki to eventually replace.
