### ISSUE TITLE
Add new Round Robin tournament from Scheduler

### ISSUE THREAD

**Issue by algomu** [TheNAF/naflm#275]
I tried to create a new RR tournament from scheduler and I get Failed request. No more information.

I select a division, check in Round robin, rounds only one and select 4 existing teams. When I click in create button I get Request Failed.

I tried with two teams and says that minimus three, I tried a name of an existing tournament and said that exists, but if I choose all correctly, only says "Request failed". Is there any place where I can see the error? Something like a log? Apache is a docker but I didn't get any error in stderr.

I tried with docker logs -f --details naflm-web, I tried also creating a volume where I can see the logs in the server:

-rw-r--r-- 1 root root     0 jul  6 16:02 other_vhosts_access.log
-rw-r--r-- 1 root root   422 jul  6 16:02 error.log
-rw-r--r-- 1 root root 14851 jul  6 16:06 access.log

But only access.log write the output. I can't find the cause

**Comment by thefloppy1** [comment]
Hi Algomu,
I have not had alot of time to work on this over the last years, this year is even worse for me, but I seem to be on the rapid slow down, so I am will setup a new install to test this issue.

cheers

**Comment by thefloppy1** [comment]
Hi Algomu,
I had to make sure I tested this correctly.

The problem you have is caused in settings_modules.php in your base directory 
Line 27
 'Scheduler'          => false, # Alternative match scheduler

replace false with true

if you set that to true, the Scheduler will now work.

**Comment by algomu** [comment]
Ohh thanks by effort, I tried, but I got Request Failed again...

I modified Scheduler from false to true, I check it and I get Request Failed again. I restarted, run maintenance and synchronisation but I get request failed always. I will try to reinstall all because I don't understand....

**Comment by thefloppy1** [comment]
Can you screenshot it for me.

**Comment by algomu** [comment]
Before click create:
![Captura de pantalla 2020-07-11 a las 11 37 14](https://user-images.githubusercontent.com/54956339/87221373-ee96d200-c36b-11ea-9d21-53a21440e68e.jpg)

The error, just after click on create button:
![Captura de pantalla 2020-07-11 a las 11 37 27](https://user-images.githubusercontent.com/54956339/87221376-f0609580-c36b-11ea-9daa-20af77d20f4f.jpg)

About settings_modules.pho:
`/*****************
 * Enable/disable modules
 *****************/
// Change value from true to false if you wish to disable a module.
$settings['modules_enabled'] = array(
    'IndcPage'           => true,  # Inducements try-out
    'PDFroster'          => true,  # Team PDF roster
    'RSSfeed'            => true,  # Site RSS feed
    'SGraph'             => true,  # Graphical statistics
    'Memmatches'         => true,  # Memorable matches viewer
    'Wanted'             => true,  # Wanted list
    'HOF'                => true,  # Hall of fame
    'Prize'              => true,  # Tournament prizes list
    'Registration'       => true,  # Allows users to register on the site.
    'Search'             => true,  # Search for coaches and teams.
    'TeamCompare'        => true,  # Team strength compare
    'Cemetery'           => true,  # Team cemetery page
    'FamousTeams'        => true,  # Famous Teams page
    'PDFMatchReport'     => true,  # Generating PDF forms for tabletop match reports.
    // The below modules are not well maintained and are poorly supported!!
    'UPLOAD_BOTOCS'      => false, # Allow upload of a BOTOCS match
    'XML_BOTOCS'         => false, # BOTOCS XML export of team
    'LeagueTables'       => true,  # Provides league table link on the main menu
    'Conference'         => true,  # Provides support for conferences within tournaments
    'Scheduler'          => true, # Alternative match scheduler
    'LeaguePref'         => true,  # Allows dynamic configuration of league preferences
    'TeamCreator'        => true,  # Allows coaches to create teams quickly
);`

**Comment by thefloppy1** [comment]
Let me do some more testing.  What are your mysql user permissions, either 
CREATE PROCEDURE
 CREATE FUNCTION
 or CREATE ROUTINE  

make sure you have the correct permissions.
I will look at something more now.

**Comment by algomu** [comment]
Hi my user is bbuser, my database naflmdb:

```
MySQL [naflmdb]> show grants;
+--------------------------------------------------------------------+
| Grants for bbuser@%                                                |
+--------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'bbuser'@'%' IDENTIFIED BY PASSWORD <secret> |
| GRANT ALL PRIVILEGES ON `naflmdb`.* TO 'bbuser'@'%'                |
+--------------------------------------------------------------------+
2 rows in set (0.00 sec)
```

**Comment by thefloppy1** [comment]
cool.  

What is your bbsite url.  and can you create me an admin user to look at it...

**Comment by algomu** [comment]
> cool.
> 
> What is your bbsite url. and can you create me an admin user to look at it...

bloodbowl.com.es:8000

test/thefloppy1

In bloodbowl.com.es you can see our actual leagues ;)

This is our test website...

**Comment by thefloppy1** [comment]
![image](https://user-images.githubusercontent.com/16111238/87222116-77d1f700-c3b4-11ea-9644-919f00bf5004.png)
Naflm doesn't like it when you do the following:
1. schedule games between teams not in the same league
2. schedule games between teams of the same person.

You will note that I scheduled a game between two teams from different coaches.  
the best way to learn what to do, is to create 6 test coaches, and a single team each.  set 5 coaches up as just coaches. 

Once you do that it should all work.
I do recommend updating your install as well.

**Comment by algomu** [comment]
Oh!!! thank I will try just now!!! to update my install, I only need to run git fetch?

**Comment by thefloppy1** [comment]
yep.

**Comment by algomu** [comment]
Something like that? I don't use git never...

```
[root@centos-bbserver naflm-master]# git fetch
From https://github.com/TheNAF/naflm
 * [new tag]         BB2016-DZ2 -> BB2016-DZ2
```

**Comment by thefloppy1** [comment]
I tend to download and update the files I need updated.

**Comment by algomu** [comment]
Thank you for your patience but, all files I can see shows, 3 years ago, 5 years ago, 11 years ago...

**Comment by thefloppy1** [comment]
download the latest zip from here.

https://github.com/TheNAF/naflm/releases/tag/BB2016-DZ2

and copy the files into your web directory. Then do the Admin ->obblm core pannel syncs.

**Comment by algomu** [comment]
thank you for all!!!!! Seems we will use the last release ;)

I will remove your user for security reasons ;)

**Comment by thefloppy1** [comment]
Sounds good to me.
