### ISSUE TITLE
On success or fail of install - install.php is renamed

### ISSUE THREAD

**Issue by thefloppy1** [TheNAF/naflm#279]
Regardless of success or fail the installer is renamed. 

need to check for success before the installer is renamed.

**Comment by snotlingorc** [comment]
Looking that the install.php, the rename is inside "if ($setupOK) {"   If the setup fails, the rename should not happen.  I am wondering if "setup_database()" has an invalid return. 

What failure is happening where the installer is renamed?

**Comment by thefloppy1** [comment]
when I test I always do the following on a new install.

I start at the beginning setting up a new DB.  I always test to make sure when you don't grant permissions the right error comes up, then grant permissions to the db run installer again, but the file was not found, it had been renamed.

**Comment by snotlingorc** [comment]
I see.  on the first time around, you do see the message "Renaming the <i>install.php</i> file from your OBBLM folder", correct?  If that is the case, then sadly, the setup_database function is not returning the correct result.

**Comment by thefloppy1** [comment]
let me cycle up a new install and I will tell you.

**Comment by thefloppy1** [comment]
I have ran the installer several times in a row, it is not the create procedure privilege that is missing it is create.  When the sql functions/procedures run it returns that the setup_database() that it is setup and correct.   The file is renamed.

Creating core tables...
FAILED — coaches
FAILED — teams
FAILED — players
FAILED — memberships
FAILED — players_skills
FAILED — races
FAILED — leagues
FAILED — divisions
FAILED — tours
FAILED — matches
FAILED — match_data
FAILED — texts
FAILED — game_data_players
FAILED — game_data_stars
FAILED — game_data_skills
FAILED — mv_players
FAILED — mv_teams
FAILED — mv_coaches
FAILED — mv_races
FAILED — mv_es_players
FAILED — mv_es_teams
FAILED — mv_es_coaches
FAILED — mv_es_races
FAILED — match_data_es
Creating module tables...
FAILED — wanted
FAILED — hof
FAILED — prizes
FAILED — log
FAILED — conferences
FAILED — conference_teams
FAILED — league_prefs
FAILED — cemetery
FAILED — famousteams
Other tasks...
FAILED — Error whilst synchronizing game data with database
FAILED — could not apply one more more table indexes
OK — created MySQL functions/procedures
FAILED — root user was not created.

Finished

**Comment by snotlingorc** [comment]
Looks like you did find something here.  Looking at lib/mysql.php (lines 974 to 1018). the setup_database function ends with return true;.  It has no error checking.

**Comment by snotlingorc** [comment]
I think you can replace the setup_database function with the following, and it will return correctly. It will now assume true unless a failure in on the functions failed  (sorry, not quite setup to do a pull request to add this in).

`function setup_database() {
    global $core_tables;
    $checks_passed = true;
    $conn = mysql_up();
    require_once('lib/class_sqlcore.php');
    // Create core tables.
    echo "<b>Creating core tables...</b><br>\n";
    foreach ($core_tables as $tblName => $def) {
        if (Table::createTable($tblName, $def)) {
            echo "<font color='green'>OK &mdash; $tblName</font><br>\n";
        } else {
            echo "<font color='red'>FAILED &mdash; $tblName</font><br>\n";
            $checks_passed=false;
        }
    }
    // Create tables used by modules.
    echo "<b>Creating module tables...</b><br>\n";
    foreach (Module::createAllRequiredTables() as $module => $tables) {
        foreach ($tables as $name => $tblStat) {
            if ($tblStat) {
                echo "<font color='green'>OK &mdash; $name</font><br>\n"
            } else {
                echo "<font color='red'>FAILED &mdash; $name</font><br>\n";
                $checks_passed=false;
            }
        }
    }
    echo "<b>Other tasks...</b><br>\n";
    if (SQLCore::syncGameData()) {
        echo "<font color='green'>OK &mdash; Synchronize game data with database</font><br>\n";
    } else {
        echo "<font color='red'>FAILED &mdash; Error whilst synchronizing game data with database</font><br>\n";
        $checks_passed=false;
    }
    if (SQLCore::installTableIndexes()) {
        echo "<font color='green'>OK &mdash; applied table indexes</font><br>\n";
    } else {
        echo "<font color='red'>FAILED &mdash; could not apply one more more table indexes</font><br>\n";
        $checks_passed=false;
    }
    if (SQLCore::installProcsAndFuncs(true)) {
        echo "<font color='green'>OK &mdash; created MySQL functions/procedures</font><br>\n"
    } else {
        echo "<font color='red'>FAILED &mdash; could not create MySQL functions/procedures</font><br>\n";
        $checks_passed=false;
    }
    // Create root user and leave welcome message on messageboard
	global $rootpass;
	$rootpass = isset($rootpass) ? $rootpass : 'root';
    if (Coach::create(array('name' => 'root', 'realname' => 'root', 'passwd' => $rootpass, 'ring' => Coach::T_RING_GLOBAL_ADMIN, 'mail' => '', 'phone' => '', 'settings' => array(), 'def_leagues' => array()))) {
        echo "<font color=green>OK &mdash; root user created.</font><br>\n";
    } else {
        echo "<font color=red>FAILED &mdash; root user was not created.</font><br>\n";
        $checks_passed=false;
    }
    Message::create(array(
        'f_coach_id' => 1,
        'f_lid'      => Message::T_BROADCAST,
        'title'      => 'OBBLM installed!',
        'msg'        => 'Congratulations! You have successfully installed Online Blood Bowl League Manager. See "About" and "Introduction" for more information.'));
    // Done!
    mysql_close($conn);
    return $checks_passed;
}`

**Comment by thefloppy1** [comment]
Tested and this can be closed.

cheers

**Comment by snotlingorc** [comment]
Just wondering, do you want to leave this open until the pull request is merged?

**Comment by thefloppy1** [comment]
That might be an idea, I may have jumped the gun a bit.
