### ISSUE TITLE
Request: More ability to select scoring and tiebreaker options

### ISSUE THREAD

**Issue by rythos42** [TheNAF/naflm#28]
I haven't looked into whether this was fixed, as I read that Shteve0's goal was to move more stuff from the back-end to the UI.

He sent me a screenshot of these 4 items in a drop-down list, and said that and round-robin vs FFA were his options. More questions could be asked about what he wants, but it's good to have this Issue here to start the discussion.

![more ability to select scoring and tiebreaker options](https://cloud.githubusercontent.com/assets/937640/10373396/fb87395c-6da1-11e5-81fe-ef349f478171.jpg)

**Comment by Shteve0** [comment]
This is back end, and I suspect will remain so. Mike has created rule
number four, and there's nothing stopping us adding extra scoring orders (I
always found the defaults quite odd to be honest!)

I think this is one of those organic things - as leagues with different
scoring forms are added, they can ask the admin (Mike or me) and we'll just
add them to the table and reinstall the back end procedures.

**Comment by rythos42** [comment]
I'm totally playing telephone with you and my commissioner here... he says:

"Why not just have custom as a fourth option, which let's you choose from a drop-down menu of available stats for 3 tie breakers?" and "Also, custom WDL points would be nice".

Since there is a method to change these ("talk to an admin") I think it's ok, as you say, to leave it in the back-end for now.

**Comment by Shteve0** [comment]
Ha, yep. Because in my (admittedly limited) experience leagues tend to
remain fairly stable with scoring, theres a limit to the utility of this
function. For the moment at least! :)
