### ISSUE TITLE
BB2020

### ISSUE THREAD

**Issue by snotlingorc** [TheNAF/naflm#291]
With the next version of BB around the corner, it looks like they have a few changes that would directly affect this.  I have not dived that deep into the code to see what all is affected. Obviously, some of the changes are still unknown.

- New/renaming of skills 
- PA stat 
  - database tables
  - Roster view/pdf
  - player view 
- Special Rules
- Tier levels
- reroll max quantity
- star player point advancements

Looks like the addition of the PA stat will be the biggest change.  Any thoughts on what it would take to add this in?  If it is major, would a new fork be warranted, so naflm2020 only supports the new rules. If you want to use crp/bb2106 rules, you have to use the current version.  

If you have a better place to discuss changes, etc, I would be interested in helping out.

**Comment by thefloppy1** [comment]
Been looking at this problem, I feel a whole new system that is a little more modern might now be needed.  

From looking at what we have seen the PA stat is new, star players etc.   it would be possible, but it might be easier to start from scratch. keep naflm as it is for 2016 leagues.

**Comment by dannyuk1982** [comment]
Closing this as OBBLM is never going to be BBSS / BB2020 compatible. A brand new system will be built.

**Comment by dannythunder** [comment]
> Closing this as OBBLM is never going to be BBSS / BB2020 compatible. **A brand new system will be built.**

Is this a fact, or a guess? What language are we talking about (hope it's not php)

**Comment by dannyuk1982** [comment]
It's what's being planned for now, whether it will ever happen is anyone's guess without a crystal ball. It's a huge project and a big ask of volunteers, although a lot of work has been done already. Nothing stopping you writing your own in whatever language you like.

**Comment by dannythunder** [comment]
> It's what's being planned for now, whether it will ever happen is anyone's guess without a crystal ball. It's a huge project and a big ask of volunteers, although a lot of work has been done already. Nothing stopping you writing your own in whatever language you like.

Ofc, but a collab would be more efficient :)

I'll for sure help out in any way I can, since this is in my interest. Php is not my preferred language tho, even If I've been coding in it :-D 

If you need any help in planning, let me know.

**Comment by dannyuk1982** [comment]
Thanks. There is a Slack group, but it's been decided to use PHP/Laravel for the build. We've had loads of people come along and say PHP is terrible and no one uses it anymore (even though it's the most popular web language by a mile), suggestions have mainly been Microsoft, but then they seem to disappear or not want to help :-/ Message me if you want an invite - dannyjrichardson at gmail
