### ISSUE TITLE
Question: Any changes to database structure?

### ISSUE THREAD

**Issue by hutchinsfairy** [TheNAF/naflm#39]
I am currently using OBBLM 0.96 and would love to give this version a go. Can I just drop the current version on top of my existing DB or are there specific changes I need to make on the database?

I'm running it on a VM so can roll it back and forth until I get bored so let me know if there's anything specific you want testing for the upgrade from 0.96.

**Comment by Shteve0** [comment]
You'd need to add certain tables to the database to get all the doubleskulls modules packaged in this version up and running.

CREATE TABLE IF NOT EXISTS conference_teams (
f_conf_id mediumint(8) unsigned NOT NULL,
f_team_id mediumint(8) unsigned NOT NULL,
PRIMARY KEY (f_conf_id,f_team_id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS conferences (
conf_id mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
f_tour_id mediumint(8) unsigned NOT NULL,
name varchar(60) DEFAULT NULL,
type tinyint(3) unsigned DEFAULT NULL,
date_created datetime DEFAULT NULL,
PRIMARY KEY (conf_id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=762 ;

CREATE TABLE IF NOT EXISTS league_prefs (
f_lid mediumint(8) unsigned NOT NULL,
prime_tid mediumint(8) unsigned DEFAULT NULL,
second_tid mediumint(8) unsigned DEFAULT NULL,
league_name varchar(128) DEFAULT NULL,
forum_url varchar(256) DEFAULT NULL,
welcome text,
rules text,
PRIMARY KEY (f_lid)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

**Comment by hutchinsfairy** [comment]
Thanks! I'll give that a whirl.
