### ISSUE TITLE
Conference plugin not working

### ISSUE THREAD

**Issue by Shteve0** [TheNAF/naflm#4]
/handler.php?type=conference

**Comment by Shteve0** [comment]
Have now switched it on, but still returns issue when I try to use the module.  Error just reads, "Error adding conference"

**Comment by rythos42** [comment]
This is because there is no "conferences" table to insert into! And unlike the last database error I looked into, there doesn't appear to be any code to create a table. 

I could try to figure out what the columns in this table are, but it would be safer if the original developer could chime in with what they were trying to do.

**Comment by Shteve0** [comment]
Nah, hold. I'll see if I can dig out the original table fields and create
them. Thanks :)

**Comment by rythos42** [comment]
I got past the "Error adding conference" by adding the tables (dev will need to run `upgrade.php` again to upgrade for this), but then there's just an input field and a label that says "Add team" and no indication of what to do next.

And I need to stop looking at this for now. :)

**Comment by Shteve0** [comment]
Here's the SQL query to build the table:

CREATE TABLE IF NOT EXISTS `conferences` (
  `conf_id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `f_tour_id` mediumint(8) unsigned NOT NULL,
  `name` varchar(60) DEFAULT NULL,
  `type` tinyint(3) unsigned DEFAULT NULL,
  `date_created` datetime DEFAULT NULL,
  PRIMARY KEY (`conf_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=762 ;

I think you might need to add a couple of entries in to start the ball rolling.  Working on League Pref now

**Comment by Shteve0** [comment]
Also

CREATE TABLE IF NOT EXISTS `conference_teams` (
  `f_conf_id` mediumint(8) unsigned NOT NULL,
  `f_team_id` mediumint(8) unsigned NOT NULL,
  PRIMARY KEY (`f_conf_id`,`f_team_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
