### ISSUE TITLE
Mobile: Upcoming matches not shown

### ISSUE THREAD

**Issue by hutchinsfairy** [TheNAF/naflm#47]
Scheduled but unsaved matches do not seem to appear in the match list.

**Comment by rythos42** [comment]
Can you tell me what steps you took to get this issue? In my testing I had no troubles Scheduling a match, and having it appear in the list -- which means I probably don't understand something! :)

**Comment by hutchinsfairy** [comment]
That's exactly what I did. I was logged in as a coach and used the mobile interface to schedule a match . Once I submitted the details I got a blank page so I reloaded the homepage and navigated back to the mobile view of matches which did not display the new scheduled match. Switching to the PC I was able to see a newly created match in "Upcoming matches". I saved this on the PC and refreshed the view on the mobile and the new match appeared.

I have not had a chance to try to recreate this I'm afraid. I'll have another go when I can and try to see if it's still a problem for me.

**Comment by hutchinsfairy** [comment]
I have identified the problem as sitting comfortably between by keyboard and chair... it appears I was confused by the sort order. Recent matches seem to appear with the newest at the top of the list and I was expecting upcoming ones to appear there also instead of beneath the oldest "recent" match.

Once saved they became a recent rather than an upcoming match and appeared where I expected them.

Any mileage in moving things around?

**Comment by rythos42** [comment]
Sorry for going dark for a month and a bit!

I just committed a fix that splits Recent and Upcoming matches in the mobile interface. Should make things a little clearer!

**Comment by rythos42** [comment]
This was fixed by separating the two match types again in mobile.
