### ISSUE TITLE
Coach stylesheet has too high a priority for multileague sites

### ISSUE THREAD

**Issue by Shteve0** [TheNAF/naflm#49]
Strange, undesirable behaviour.

1) guest not logged in: sees league settings for language, stylesheet. Can change league view freely.
2) admin logged in: sees own settings for language, stylesheet. Can change league view freely.
3) coach logged in: sees own settings for language, stylesheet. Can not change league view to any league but their own.

Really we want everything to be like 1, except for in things like the league preferences menu.

**Comment by Shteve0** [comment]
The skin issue I think we can resolve by making the coach's stylesheet setting blank, removing it from the coach menu options, and stopping it updating (which it does frequently).

Alternatively we could just ignore it and strip the check for coach preference out of the options (though the home league settings would still potentially prevent this resolving the issue).

Alternatively we could add an option that's checked in the stylesheet settings as to whether the coach has activated "override league skin with my skin preference", which would itself need to be a new option in the coach menu.  This could/should be "no" by default.

**Comment by Shteve0** [comment]
I'm splitting out the unable to view other league issue into a new issue and will rename this thread.

**Comment by rythos42** [comment]
Steve wrote an e-mail to me, saying:

1) registering a new account to your league and logging in with it. Then try any way you can think of to look at any page of a different league!

2) using your own account to look at the Australian league. Then log out and have a look again - the skin is different.

**Comment by rythos42** [comment]
Hey @Shteve0, I did some refactoring to make this easier (centralizing where the stylesheet ID was coming from). When I tested the refactoring locally...the stylesheet changed when it hadn't been changing before. 

Can you test your test cases on thenafdev and see if what you want to happen is happening? It was really odd.

**Comment by rythos42** [comment]
Looking at this a bit further -- I don't know why we offer stylesheet selection for coaches. There really isn't any support for it -- the dropdown under Profile to select a theme is hard coded to have a single value of "1", there's no code to load other sheets. And really, you likely want to see the stylesheet for the league that you're in.

I would advocate removing the theme selection code, as well as simplifying the new method $coach->getStylesheetId to return the league sheet in all situations. There is always a league selected, that I can see.

**Comment by rythos42** [comment]
During my Friday fumbling around today my refactoring "screwed something up", which actually ended up implementing ignoring the coaches stylesheet, is why it was being odd.

So I fixed that issue, and am currently ignoring the coaches stylesheet. :P 

If you think it's a worthwhile feature, I can add an Issue to make it actually useful. Otherwise, I think I'll leave it like this.

(but I still need/want to remove the Profile setting, after Steve gets a moment to read all this spam and say he's ok losing the feature for now :))

**Comment by thefloppy1** [comment]
Surely leagues want to push a standard look and feel, I think it be better to have the css set by admin.

**Comment by rythos42** [comment]
One agreement is all I need! I'm taking it out! :)

**Comment by rythos42** [comment]
It's gone. If anyone thinks it's a good idea to have it, we can have a feature request to add it for real, instead of the half-measure it was. But I don't think it's a useful feature -- as you say, better to be set for each league.
