### ISSUE TITLE
LeaguePref module "unable to save".  Permissions issue?

### ISSUE THREAD

**Issue by Shteve0** [TheNAF/naflm#5]
Testers will require commissioner rights

**Comment by Shteve0** [comment]
Still trying to dig into this. Have been pulling my hair out most of the afternoon. No matter what I try, 'unable to save preferences'. Giving up, will come back to it with fresh eyes soon.

**Comment by mfranchetti** [comment]
May or may not be related, but the League/Division/Tournament admin pages don't seem to be working. I'm just seeing blank pages (below the header and menu bar)

**Comment by Shteve0** [comment]
Could be my tinkering with the sections file has made it worse (only in the live version, not a commit). Is your error on the public demo or on a local copy?

**Comment by mfranchetti** [comment]
On the public demo

**Comment by Shteve0** [comment]
Yeah, my bad. I'll roll back the changes first thing tomorrow - it seems I went too far back in the history looking for the changes. Have been in touch with doubleskulls and he's very kindly offered to take a look at the weekend.

**Comment by Shteve0** [comment]
Okay, looks to have been a rogue <?php at the end of the admin_nodes file.  I've removed it and it seems to have cleared up the issue of the missing l/d/t admin menu tables.  Site is now up to date other than that it has some adds yet to be deployed to the github

**Comment by mfranchetti** [comment]
Updated the LeaguePreferences module to correct saving to database. However, changes still not reflected on league page.

**Comment by Shteve0** [comment]
Used the following to create the correct table.  Submitting entries does nothing; need to insert entries manually; can only call to the first entry in the list.

Reopening issue.

DROP TABLE IF EXISTS `league_prefs`;
CREATE TABLE IF NOT EXISTS `league_prefs` (
  `f_lid` mediumint(8) unsigned NOT NULL,
  `prime_tid` mediumint(8) unsigned DEFAULT NULL,
  `second_tid` mediumint(8) unsigned DEFAULT NULL,
  `league_name` varchar(128) DEFAULT NULL,
  `forum_url` varchar(256) DEFAULT NULL,
  `welcome` text,
  `rules` text,
  PRIMARY KEY (`f_lid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

**Comment by Shteve0** [comment]
The LeaguePref module was clearing the lid (to zero) and then attempting to reset it to the home league of the person browsing, though that was going weird.  To get around it I just turned those lines off.

/*public $lid      = 0;*/

/*    $sel_lid = (is_object($coach) && isset($coach->settings['home_lid']) && in_array($coach->settings['home_lid'], array_keys($leagues))) ? $coach->settings['home_lid'] : $settings['default_visitor_league'];
*/

Issue now is that this test is failing:

	// check this coach is allowed to administer this league
	$canEdit = is_object($coach) && $coach->isNodeCommish(T_NODE_LEAGUE, $l_pref->lid) ? "" : "DISABLED";

As a result the LeaguePref is returning the correct league admin menu for the league you're looking at, but it's uneditable.  Progress... of sorts :)

**Comment by Shteve0** [comment]
That issue appears to have been fixed by reactivating the second line "$sel_lid...".

Looks good!

**Comment by Shteve0** [comment]
Still an issue for those with admin rights to more than one league - the pref menu simply defaults to the first available lid, it seems (as a universal admin I'm unable to call up access to lid=5, for example.

**Comment by Shteve0** [comment]
Think this is now fixed!

Delete: $sel_lid = (is_object($coach) && isset($coach->settings['home_lid']) && in_array($coach->settings['home_lid'], array_keys($leagues))) ? $coach->settings['home_lid'] : $settings['default_visitor_league'];

Insert: list($sel_lid, $HTML_LeagueSelector) = HTMLOUT::simpleLeagueSelector();
echo $HTML_LeagueSelector;

A little more testing necessary but it seems that this function allows admins to call all leagues, and commissioners to call their own. If there's no row for the league in the table then results are returned but I can't overwrite the content with a save; if I add the row manually to the table, however, I can edit it (with the correct permissions).

Awesome.

**Comment by Shteve0** [comment]
Fixed in 9b8ffd8
