### ISSUE TITLE
Auto-create settings file for new league

### ISSUE THREAD

**Issue by Shteve0** [TheNAF/naflm#60]
Creating a league is still too manual.

When a league is created, we should:
1. Autocreate an entry in the leaguepref table
2. Autocreate a localsettings file

**Comment by Shteve0** [comment]
I imagine the best way to do the second bit, short term, is to have a settings_X in localsettings that's replicated and renamed in line with the new league (assuming there isn't one already).

A cleaner and potentially better long term solution might just be to do away with having all the separate settings files and going big on the leaguepref table. Slightly bigger project, but potentially rewarding. It'd need to include (over and above the existing options):

[ ] Starting TV for new teams
[ ] Stylesheet
[ ] Country (for menu system)
[ ] City or area covered (for menu system, populate from location on creation)
[ ] league logo upload (capped at same size as Naf logo, I'll handle the integration with the stylesheet)
[?] league language

Anything I've missed?

**Comment by thefloppy1** [comment]
Great Idea.

I would also add
[]extra teams -2015 unoff. and off teams

**Comment by rythos42** [comment]
I did the LeaguePrefs entry work -- this database row will be created when you save a new LeaguePref for a new league. (So don't panic if you don't see the row before you hit Save on the LeaguePref page!)

Country/Area would be great to help support better menu creation for #15.

**Comment by rythos42** [comment]
Just renaming this since I think that's what this Issue is about now. The Country/Area is contained in #15, and the LeaguePrefs work is finished.

**Comment by rythos42** [comment]
I promised I'd do this Issue once it got annoying to create this file manually, so here it is. I have 2 league creation requests in my inbox, and I don't want to do this part of the task anymore. :P

**Comment by Shteve0** [comment]
Awesome. This is a great step - one of the very few remaining steps
required to be completed in the backend.   Great work :)

**Comment by rythos42** [comment]
Apparently I forgot something. Tested it locally again and I'm satisfied this works, so I'm going to close it.
