### ISSUE TITLE
LeagueTables section not working?

### ISSUE THREAD

**Issue by Shteve0** [TheNAF/naflm#7]
Expected functionality not appearing at:

/handler.php?type=leaguetables

**Comment by williamleonard** [comment]
You had it set to false in: settings_modules.php

**Comment by Shteve0** [comment]
I'm an idiot.  Thanks :)

**Comment by Shteve0** [comment]
Reopening - unfortunately tables are still not populating...?

http://thenafdev.obblm.com/handler.php?type=leaguetables

**Comment by Shteve0** [comment]
Actually fixed now in release 9b8ffd8
