### ISSUE TITLE
NYCBBL League missing from Menu Bar

### ISSUE THREAD

**Issue by andrewweakland** [TheNAF/naflm#73]
Any recent updates roll out? As our league no longer appears under 'USA' in the dropdown as it did the last time I checked...

![nycbbl missing](https://cloud.githubusercontent.com/assets/16119321/12824649/3f892fb0-cb40-11e5-96f9-f46b7eaa600f.png)

It appears a few other leagues are missing as well.

**Comment by rythos42** [comment]
Thanks for the report! I'm doing a new deployment method that's had some unforeseen side effects and this is one of them.

I've fixed it and have rolled out the change to the server so your league should exist again.

Feel free to log any other issues you see!
