### ISSUE TITLE
PDF Match report: Erroneous zeros

### ISSUE THREAD

**Issue by hutchinsfairy** [TheNAF/naflm#76]
In commit 2b0f403cf9cf6a57cdad3cc4fa91dec542330d7f the match report was changed to include Apo, FF, etc but these always seem to show as 0, even when they shouldn't.

**Comment by thefloppy1** [comment]
No they shouldn't my test server shows what that the Apo and FF are. It could be calling the wrong field name. I will look at it in the morning.

**Comment by thefloppy1** [comment]
Ok tested, verified and found the problem.
Apo had a small spelling error, oops.
FF was calling the wrong field, changed to rg_ff and it shows up

**Comment by rythos42** [comment]
Nice! I got this file from Steve, and committed it.
