### ISSUE TITLE
optional Roster Bretonnian Not loading in to the DB

### ISSUE THREAD

**Issue by thefloppy1** [TheNAF/naflm#80]
Via the menu Game Rules -> optional Roster -> Bretonnian
is returning
The specified ID does not exist.
As far as I can tell it is inconsistent naming of the files, and calls to the Race name etc.  The option is on, but it is not loading.

**Comment by thefloppy1** [comment]
Update the error is in the setting.php

$settings['custom_races'] = array(
    'Brettonia'         => true,

Correct spelling for it to work is   'Bretonnia'

**Comment by rythos42** [comment]
I swear I've fixed this twice already. >.<

As well as the setting.php issue, it's important to note that you have to re-sync the database after changing the `custom_races` variables.

**Comment by thefloppy1** [comment]
Except this was found doing a new install. so I did the settings.php before I run the installer.

**Comment by rythos42** [comment]
I updated the committed settings.php to have the correct spelling.

I'm going to leave this Issue open until I get it pushed to thenafdev -- have to do it manually since the settings on GH aren't the ones for thenafdev.

**Comment by rythos42** [comment]
Actually, it looks like thenafdev should have the correct spelling, so this fix is just for new installs.
