### ISSUE TITLE
Win % is calculating with draws?

### ISSUE THREAD

**Issue by thefloppy1** [TheNAF/naflm#81]
The win % is calculating 2 Draws as a win, win % should be wins against games. 

From class_sqlcore.php
BEGIN
            RETURN IFNULL(100*(won+draw/2)/played,0);
        END

If it is a true win% then draws should not ever be used. it should be only Wins.

**Comment by Shteve0** [comment]
Not wrong per se, just a different arrangement. That's how the old BBRC
used to calculate win% of teams and how the term is used for tier
discussions.

**Comment by thefloppy1** [comment]
Yes I can see why it was done this way, however that is not a win%.
