### ISSUE TITLE
Show League ID after creation

### ISSUE THREAD

**Issue by rythos42** [TheNAF/naflm#86]
As a global admin, you need the league ID to create a settings file. Needing to poke around for this ID is annoying, and probably unnecessary since it's likely right there on return when we create the ID.

Just a simple line like "League created with ID <x>".

**Comment by hutchinsfairy** [comment]
Is this still necessary after #60?

**Comment by rythos42** [comment]
Unfortunately you still need the information because you still need it when adding the league to the Home menu.

However, #104 could be used in place of this while we wait for the league menu to be made dynamic in #15. As well, I've tended to just use browser Developer Tools to get the LID from whatever drop down list is being displayed. :P
