### ISSUE TITLE
Move databe-specifc configuration from settings.php to config.php

### ISSUE THREAD

**Issue by jgmorse** [TheNAF/naflm#98]
Currently $db_name, $db_user, $db_passwd are defined in both settings.php and config.php.  This is confusing for new installers.  Can these and $db_host be moved exclusively to config.php, and config.php added to .gitignore, so installers and potential code contributors can manage sensitive data securely?

**Comment by rythos42** [comment]
I went the other way and deleted config.php and removed references to it in the deployment.

If we have this config.php that isn't in the repo but is referenced, new installers might believe they are missing an important file. As well, having a secondary file that shouldn't be committed doesn't help much -- we've just added another file that developers need to tip-toe around, as well as complicated new installation.

On the other side, upgrades are going to be annoying either way. If we've added features to the files, admins will need to manually merge those features in while maintaining their own settings.

I think that this *should be* a developer education issue to not commit these files: https://github.com/TheNAF/naflm/wiki/Developers, and an admin education on how to upgrade.
