### ISSUE TITLE
Clean up .gitnore

### ISSUE THREAD

**Issue by jgmorse** [TheNAF/naflm#99]
.gitignore can be cleaned up and future-proofed by using wildcard matching, as in:
`localsettings/settings_*.php`

I would also recommend adding config.php to .gitignore.

**Comment by rythos42** [comment]
I've found .gitignore super hard to get used to (I usually live in SVN). But the confusion is simply this -- if you add something to gitignore that's already in the repo, it won't be ignored. You have to delete it from git, then ignore it to get what you want. 

There's a pile of ignores in this file that don't do what the initial author thought they would.

**Comment by rythos42** [comment]
All of the files in .gitignore were already in the repo, so they weren't doing anything at all. 

I removed every line except config.php, which is not in the repo. (and is of questionable value).
